

# This file was *autogenerated* from the file exp_W7h.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65 = Integer(65); _sage_const_42 = Integer(42); _sage_const_24 = Integer(24); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_4 = Integer(4); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_2 = Integer(2); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_25 = Integer(25); _sage_const_3p0 = RealNumber('3.0'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_0p85 = RealNumber('0.85'); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_0p0 = RealNumber('0.0'); _sage_const_99 = Integer(99); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_30 = Integer(30); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_150 = Integer(150); _sage_const_62 = Integer(62); _sage_const_35 = Integer(35); _sage_const_14 = Integer(14); _sage_const_12 = Integer(12); _sage_const_8 = Integer(8); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p5 = RealNumber('1.5'); _sage_const_11 = Integer(11); _sage_const_9 = Integer(9); _sage_const_18 = Integer(18); _sage_const_60 = Integer(60); _sage_const_16 = Integer(16); _sage_const_40 = Integer(40)#!/usr/bin/env sage
# exp_W7h.sage — 2段階スクリーニング: cycle type × Burau trace
# 戦略比較: ランダム / グローバルBurau / 2段階 / オラクル

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from collections import defaultdict
from sklearn.cluster import KMeans
from pathlib import Path
from sage.combinat.permutation import Permutation as SagePerm
from itertools import permutations as iter_perms

print("=" * _sage_const_65 )
print("  W-7h: 2段階スクリーニング設計の検証")
print("  Stage1: cycle type 分類  Stage2: 型内 Burau ランキング")
print("=" * _sage_const_65 )

OUT = Path("/mnt/c/Users/yoshi/don_theory/lab/wild/results/W7h")
OUT.mkdir(parents=True, exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# 数値セットアップ（W-7g と同一 seed）
# ══════════════════════════════════════════════════════════════════
rng = np.random.default_rng(int(_sage_const_42 ))
d   = _sage_const_24 
A_dyn  = rng.standard_normal((d,d))*_sage_const_0p25 ;  A_dyn = A_dyn - A_dyn.T
b_bias = rng.standard_normal(d)*_sage_const_0p1 
a_vec  = np.zeros(d);  a_vec[:d//_sage_const_4 ] = _sage_const_1p0 
M_mat  = rng.standard_normal((d,d))*_sage_const_0p3 
M_mat  = M_mat / (np.linalg.norm(M_mat,_sage_const_2 )+_sage_const_1en8 )
bias_list = [rng.standard_normal(d)*(_sage_const_0p2 +_sage_const_0p05 *i) for i in range(_sage_const_4 )]
theta_star = np.array([_sage_const_1p0 , _sage_const_1p0 ])
p0_master  = rng.standard_normal(d)*_sage_const_0p5 
N_ROUNDS = _sage_const_2 ;  N_GRID = _sage_const_25 
th1 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)
th2 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)

def time_ev(p): return np.tanh(A_dyn@p+b_bias)*_sage_const_0p5 +p*_sage_const_0p4 
def make_ops(K):
    return [
        lambda p,th,_=None: p+th[_sage_const_0 ]*a_vec,
        lambda p,th,_=None: (np.eye(d)+th[_sage_const_1 ]*M_mat)@p,
        lambda p,th,_=None: np.tanh(p*_sage_const_1p2 )*_sage_const_0p9 ,
        lambda p,th,_=None: np.tanh(p*_sage_const_0p8 +bias_list[_sage_const_0 ])*_sage_const_0p7 ,
        lambda p,th,_=None: p*_sage_const_0p6 +np.tanh(bias_list[_sage_const_1 ])*_sage_const_0p4 ,
        lambda p,th,_=None: np.tanh(p+bias_list[_sage_const_2 ])*_sage_const_0p85 ,
    ][:K]

def compute_dist(order, K):
    ops = make_ops(K);  p0 = p0_master.copy()
    ref = list(range(K))
    def traj(ord_, th):
        p = p0.copy();  t = [p.copy()]
        for _ in range(N_ROUNDS):
            for idx in ord_:
                p = time_ev(p);  p = ops[idx](p,th);  t.append(p.copy())
        return np.array(t)
    zt = traj(ref, theta_star)
    def J(ord_, th): return float(np.mean(np.sum((traj(ord_,th)-zt)**_sage_const_2 ,axis=_sage_const_1 )))
    grid = np.array([[J(order,[th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    ref_g= np.array([[J(ref,  [th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    return float(np.sqrt(np.mean((grid.ravel()-ref_g.ravel())**_sage_const_2 )))

# ══════════════════════════════════════════════════════════════════
# データ構築: K=4, K=6
# ══════════════════════════════════════════════════════════════════
ALL = {}
for K in [_sage_const_4 , _sage_const_6 ]:
    print(f"\n[K={K}] 全 {factorial(K)} 件のデータ構築中...")
    BK = BraidGroup(K);  gK = list(BK.generators())
    rows = []
    for perm in iter_perms(range(_sage_const_1 , K+_sage_const_1 )):
        sp = SagePerm(list(perm))
        b  = BK.one()
        for i in sp.reduced_word(): b = b * gK[i-_sage_const_1 ]
        btr = float(b.burau_matrix()(t=QQ(_sage_const_1 )/QQ(_sage_const_2 )).trace())
        ct  = str(list(sp.cycle_type()))
        dist= compute_dist([x-_sage_const_1  for x in perm], K)
        rows.append({"perm": list(perm), "label": "".join(str(x) for x in perm),
                     "burau": btr, "writhe": len(sp.reduced_word()),
                     "dist": dist, "ct": ct})
    ALL[K] = rows
    dists = [r["dist"] for r in rows]
    print(f"  完了。dist: [{min(dists):.3f}, {max(dists):.3f}]  "
          f"mean={np.mean(dists):.3f}")

# ══════════════════════════════════════════════════════════════════
# 2段階モデルの構築
# ══════════════════════════════════════════════════════════════════
def build_twostage_model(rows):
    """
    各 cycle type について:
      - within-type Pearson r を計算
      - r の符号から「高い Burau が良いか低い Burau が良いか」を決定
    戻り値: dict{ct: {"r": r, "direction": +1 or -1, "n": n, "mean_dist": mean}}
    """
    ct_groups = defaultdict(list)
    for r in rows: ct_groups[r["ct"]].append(r)
    model = {}
    for ct, grp in ct_groups.items():
        bv = np.array([r["burau"] for r in grp])
        dv = np.array([r["dist"]  for r in grp])
        if len(grp) >= _sage_const_3 :
            rr, pp = stats.pearsonr(bv, dv)
        else:
            rr, pp = _sage_const_0p0 , _sage_const_1p0 
        # r < 0: 高 Burau → 低 dist → 高い順に選ぶ (direction=+1)
        # r > 0: 高 Burau → 高 dist → 低い順に選ぶ (direction=-1)
        direction = -_sage_const_1  if rr > _sage_const_0  else +_sage_const_1 
        model[ct] = {"r": rr, "p": pp, "direction": direction,
                     "n": len(grp), "mean_dist": float(dv.mean())}
    return model, ct_groups

# ══════════════════════════════════════════════════════════════════
# スクリーニング戦略の定義
# ══════════════════════════════════════════════════════════════════
def strategy_random(rows, N, seed=_sage_const_0 ):
    idx = np.random.default_rng(int(seed)).choice(len(rows), N, replace=False)
    return [rows[i] for i in idx]

def strategy_global_burau(rows, N):
    """グローバル Burau 降順（高い = 単純 = 良いはず）"""
    return sorted(rows, key=lambda r: -r["burau"])[:N]

def strategy_twostage(rows, N, model, ct_groups):
    """
    Stage1: cycle type 別に候補を Burau でランキング（方向を type ごとに調整）
    Stage2: 各 type から cycle_type_size / total * N 件を比例配分で選択
    """
    total = len(rows)
    selected = []
    for ct, grp in ct_groups.items():
        n_select = max(_sage_const_1 , round(N * len(grp) / total))
        direction = model[ct]["direction"]
        # direction=+1: 高 Burau 優先, direction=-1: 低 Burau 優先
        ranked = sorted(grp, key=lambda r: direction * r["burau"], reverse=True)
        selected.extend(ranked[:n_select])
    # 超過分を除去（mean_dist が小さい型から優先して保持）
    if len(selected) > N:
        selected = sorted(selected, key=lambda r: r["dist"])[:N]
    # 不足分を補填（残りをランダムに）
    elif len(selected) < N:
        selected_labels = {r["label"] for r in selected}
        remaining = [r for r in rows if r["label"] not in selected_labels]
        np.random.default_rng(int(_sage_const_99 )).shuffle(remaining)
        selected.extend(remaining[:N - len(selected)])
    return selected[:N]

def strategy_oracle(rows, N):
    """真の上位 N 件（実際には使えないオラクル）"""
    return sorted(rows, key=lambda r: r["dist"])[:N]

def evaluate(selected):
    dists = np.array([r["dist"] for r in selected])
    return {"mean": float(dists.mean()), "std": float(dists.std()),
            "max": float(dists.max()), "min": float(dists.min())}

# ══════════════════════════════════════════════════════════════════
# 主要実験: 各 N で 4 戦略を比較
# ══════════════════════════════════════════════════════════════════
print("\n[メイン比較] 各 N でのスクリーニング性能")
print("=" * _sage_const_65 )

results_by_K = {}
for K in [_sage_const_4 , _sage_const_6 ]:
    rows = ALL[K]
    model, ct_groups = build_twostage_model(rows)
    total = len(rows)

    print(f"\n  ── K={K} ({total} 通り) ──")
    print(f"\n  [2段階モデル: cycle type ごとの方向]")
    for ct, info in sorted(model.items(), key=lambda x: x[_sage_const_1 ]["mean_dist"]):
        sign = "↑高Burau優先" if info["direction"]==+_sage_const_1  else "↓低Burau優先"
        print(f"    {ct:<25} n={info['n']:3d}  "
              f"mean_dist={info['mean_dist']:.3f}  "
              f"within_r={info['r']:+.3f}  {sign}")

    N_values = [_sage_const_3 , _sage_const_5 , _sage_const_10 , _sage_const_20 , _sage_const_30 ] if K == _sage_const_4  else [_sage_const_10 , _sage_const_20 , _sage_const_50 , _sage_const_100 , _sage_const_150 ]
    N_values = [n for n in N_values if n < total]

    perf = defaultdict(list)
    print(f"\n  N_sel  | Random       | GlobalBurau  | 2-Stage      | Oracle")
    print(f"  " + "-"*_sage_const_62 )
    for N in N_values:
        # 30回ランダムの平均
        rand_means = [evaluate(strategy_random(rows, N, seed=s))["mean"]
                      for s in range(_sage_const_30 )]
        r_m = np.mean(rand_means);  r_s = np.std(rand_means)
        gb = evaluate(strategy_global_burau(rows, N))
        ts = evaluate(strategy_twostage(rows, N, model, ct_groups))
        oc = evaluate(strategy_oracle(rows, N))
        print(f"  N={N:<4} | {r_m:.3f}±{r_s:.3f} | "
              f"{gb['mean']:.3f}±{gb['std']:.3f} | "
              f"{ts['mean']:.3f}±{ts['std']:.3f} | "
              f"{oc['mean']:.3f}±{oc['std']:.3f}")
        perf["random_mean"].append(r_m);  perf["random_std"].append(r_s)
        perf["global_mean"].append(gb["mean"])
        perf["twostage_mean"].append(ts["mean"])
        perf["oracle_mean"].append(oc["mean"])
        perf["N"].append(N)

    results_by_K[K] = {"perf": perf, "model": model,
                       "ct_groups": ct_groups, "rows": rows}

    # Precision@N (何件本当の上位 N を取れたか)
    true_top = {r["label"] for r in strategy_oracle(rows, max(N_values))}
    print(f"\n  [Precision@N — 真の上位N件のうち何件を取れたか]")
    print(f"  N_sel  | GlobalBurau  | 2-Stage")
    print(f"  " + "-"*_sage_const_35 )
    for N in N_values:
        true_topN = {r["label"] for r in strategy_oracle(rows, N)}
        gb_sel  = {r["label"] for r in strategy_global_burau(rows, N)}
        ts_sel  = {r["label"] for r in
                   strategy_twostage(rows, N, model, ct_groups)}
        p_gb = float(len(true_topN & gb_sel)) / float(N)
        p_ts = float(len(true_topN & ts_sel)) / float(N)
        print(f"  N={N:<4} | {p_gb:.3f}         | {p_ts:.3f}")

# ══════════════════════════════════════════════════════════════════
# 可視化
# ══════════════════════════════════════════════════════════════════
print("\n[可視化]")

# ── 図1: K=6 の 4 戦略パフォーマンス比較 ───────────────────────
K = _sage_const_6 
rows   = ALL[K]
model, ct_groups = build_twostage_model(rows)
perf   = results_by_K[K]["perf"]
N_vals = perf["N"]
all_dists = np.array([r["dist"] for r in rows])

fig, axes = plt.subplots(_sage_const_1 , _sage_const_2 , figsize=(_sage_const_14 , _sage_const_6 ))
fig.suptitle(f"W-7h: 2-Stage Screening vs Alternatives  (K={K}, n=720)", fontsize=_sage_const_12 )

ax = axes[_sage_const_0 ]
ax.plot(N_vals, perf["random_mean"],   "o--", color="gray",      lw=_sage_const_2 , ms=_sage_const_8 , label="Random")
ax.plot(N_vals, perf["global_mean"],   "s-",  color="steelblue", lw=_sage_const_2 , ms=_sage_const_8 , label="Global Burau")
ax.plot(N_vals, perf["twostage_mean"], "^-",  color="tomato",    lw=_sage_const_2p5 , ms=_sage_const_10 , label="2-Stage (ct+Burau)")
ax.plot(N_vals, perf["oracle_mean"],   "D--", color="green",     lw=_sage_const_1p5 , ms=_sage_const_8 , label="Oracle (upper bound)")
ax.axhline(all_dists.mean(), color="black", lw=_sage_const_1 , linestyle=":", alpha=_sage_const_0p5 ,
           label=f"pop mean={all_dists.mean():.2f}")
ax.set_xlabel("N selected", fontsize=_sage_const_11 );  ax.set_ylabel("Mean landscape distance", fontsize=_sage_const_11 )
ax.set_title("Mean distance of selected N orderings\n(lower = better screening)", fontsize=_sage_const_10 )
ax.legend(fontsize=_sage_const_9 );  ax.grid(True, alpha=_sage_const_0p3 )

# 改善率
ax2 = axes[_sage_const_1 ]
rand_arr = np.array(perf["random_mean"])
gb_arr   = np.array(perf["global_mean"])
ts_arr   = np.array(perf["twostage_mean"])
oc_arr   = np.array(perf["oracle_mean"])
gb_imp   = (rand_arr - gb_arr) / rand_arr * _sage_const_100 
ts_imp   = (rand_arr - ts_arr) / rand_arr * _sage_const_100 
oc_imp   = (rand_arr - oc_arr) / rand_arr * _sage_const_100 

ax2.plot(N_vals, gb_imp, "s-",  color="steelblue", lw=_sage_const_2 , ms=_sage_const_8 , label="Global Burau")
ax2.plot(N_vals, ts_imp, "^-",  color="tomato",    lw=_sage_const_2p5 , ms=_sage_const_10 , label="2-Stage")
ax2.plot(N_vals, oc_imp, "D--", color="green",     lw=_sage_const_1p5 , ms=_sage_const_8 , label="Oracle")
ax2.axhline(_sage_const_0 , color="black", lw=_sage_const_1 , alpha=_sage_const_0p5 )
ax2.set_xlabel("N selected", fontsize=_sage_const_11 )
ax2.set_ylabel("Improvement over random (%)", fontsize=_sage_const_11 )
ax2.set_title("% improvement in mean dist vs random\n(higher = better)", fontsize=_sage_const_10 )
ax2.legend(fontsize=_sage_const_9 );  ax2.grid(True, alpha=_sage_const_0p3 )

plt.tight_layout()
p = OUT / "W7h_fig1_strategy_comparison.png"
fig.savefig(str(p), dpi=_sage_const_150 , bbox_inches="tight");  plt.close()
print(f"  fig1 saved: {p}")

# ── 図2: K=6 — cycle type 別の選択可視化 ──────────────────────
N_demo = _sage_const_50 
rows6    = ALL[_sage_const_6 ]
model6, ct_groups6 = build_twostage_model(rows6)
gb_sel50  = set(r["label"] for r in strategy_global_burau(rows6, N_demo))
ts_sel50  = set(r["label"] for r in strategy_twostage(rows6, N_demo, model6, ct_groups6))
oc_sel50  = set(r["label"] for r in strategy_oracle(rows6, N_demo))

burau6 = np.array([r["burau"] for r in rows6])
dist6  = np.array([r["dist"]  for r in rows6])
types6 = [r["ct"] for r in rows6]
unique_cts6 = sorted(set(types6))
ct_cmap = {ct: plt.cm.tab20(i/len(unique_cts6)) for i,ct in enumerate(unique_cts6)}

fig, axes = plt.subplots(_sage_const_1 , _sage_const_3 , figsize=(_sage_const_18 , _sage_const_6 ))
fig.suptitle(f"W-7h: N={N_demo} selected orderings (K=6, n=720)", fontsize=_sage_const_12 )

panels = [
    ("GlobalBurau", gb_sel50, "steelblue"),
    ("2-Stage",     ts_sel50, "tomato"),
    ("Oracle",      oc_sel50, "green"),
]
for ax, (name, sel, hi_color) in zip(axes, panels):
    for ct in unique_cts6:
        mask = np.array(types6) == ct
        c = ct_cmap[ct]
        ax.scatter(burau6[mask], dist6[mask], s=_sage_const_12 , alpha=_sage_const_0p25 , color=c, zorder=_sage_const_2 )
    # 選択された点を強調
    sel_mask = np.array([r["label"] in sel for r in rows6])
    ax.scatter(burau6[sel_mask], dist6[sel_mask], s=_sage_const_60 , color=hi_color,
               edgecolors="black", lw=_sage_const_0p8 , zorder=_sage_const_5 , alpha=_sage_const_0p9 )
    mean_sel = dist6[sel_mask].mean() if sel_mask.sum() > _sage_const_0  else _sage_const_0 
    ax.set_xlabel("Burau trace");  ax.set_ylabel("Landscape distance")
    ax.set_title(f"{name}\nmean dist of selected = {mean_sel:.3f}", fontsize=_sage_const_10 )
    ax.grid(True, alpha=_sage_const_0p3 )

plt.tight_layout()
p = OUT / "W7h_fig2_selection_viz.png"
fig.savefig(str(p), dpi=_sage_const_150 , bbox_inches="tight");  plt.close()
print(f"  fig2 saved: {p}")

# ── 図3: cycle type 別の「方向付き Burau」の有効性 ─────────────
fig, axes = plt.subplots(_sage_const_2 , _sage_const_3 , figsize=(_sage_const_16 , _sage_const_11 ))
fig.suptitle("W-7h: Within-cycle-type Burau screening (K=6)", fontsize=_sage_const_12 )

ct_sorted_by_n = sorted(ct_groups6.items(), key=lambda x: -len(x[_sage_const_1 ]))[:_sage_const_6 ]
for ax, (ct, grp) in zip(axes.flat, ct_sorted_by_n):
    bv = np.array([r["burau"] for r in grp])
    dv = np.array([r["dist"]  for r in grp])
    rr = model6[ct]["r"]
    direction = model6[ct]["direction"]

    ax.scatter(bv, dv, s=_sage_const_40 , alpha=_sage_const_0p7 ,
               color=ct_cmap.get(ct, "gray"), edgecolors="black", lw=_sage_const_0p3 )
    # 回帰直線
    if len(grp) >= _sage_const_3 :
        sl, ic, *_ = stats.linregress(bv, dv)
        xs = np.linspace(bv.min(), bv.max(), _sage_const_50 )
        ax.plot(xs, sl*xs+ic, "r--", lw=_sage_const_1p5 )
    # 選択される側を矢印で示す
    dir_text = "Select HIGH Burau" if direction==+_sage_const_1  else "Select LOW Burau"
    dir_color= "steelblue"         if direction==+_sage_const_1  else "tomato"
    ax.set_xlabel("Burau trace", fontsize=_sage_const_9 );  ax.set_ylabel("Landscape dist", fontsize=_sage_const_9 )
    ax.set_title(f"cycle type = {ct}\nn={len(grp)},  r={rr:+.3f}\n{dir_text}",
                 fontsize=_sage_const_9 , color=dir_color)
    ax.grid(True, alpha=_sage_const_0p3 )

plt.tight_layout()
p = OUT / "W7h_fig3_within_ct.png"
fig.savefig(str(p), dpi=_sage_const_150 , bbox_inches="tight");  plt.close()
print(f"  fig3 saved: {p}")

# ══════════════════════════════════════════════════════════════════
# サマリー
# ══════════════════════════════════════════════════════════════════
print("\n" + "="*_sage_const_65 )
print("  総合サマリー")
print("="*_sage_const_65 )

for K in [_sage_const_4 , _sage_const_6 ]:
    rows  = ALL[K]
    perf  = results_by_K[K]["perf"]
    model = results_by_K[K]["model"]
    all_d = np.array([r["dist"] for r in rows])

    print(f"\n  ── K={K} ({len(rows)} 通り) ──")
    print(f"  全体平均距離: {all_d.mean():.4f}")

    # N=20 の比較
    N_target = _sage_const_20  if K == _sage_const_6  else _sage_const_5 
    if N_target in perf["N"]:
        idx = perf["N"].index(N_target)
        print(f"\n  N={N_target} のスクリーニング比較:")
        print(f"    Random:       mean={perf['random_mean'][idx]:.4f}")
        print(f"    GlobalBurau:  mean={perf['global_mean'][idx]:.4f}  "
              f"(+{(perf['random_mean'][idx]-perf['global_mean'][idx])/perf['random_mean'][idx]*_sage_const_100 :.1f}%改善)")
        print(f"    2-Stage:      mean={perf['twostage_mean'][idx]:.4f}  "
              f"(+{(perf['random_mean'][idx]-perf['twostage_mean'][idx])/perf['random_mean'][idx]*_sage_const_100 :.1f}%改善)")
        print(f"    Oracle:       mean={perf['oracle_mean'][idx]:.4f}  "
              f"(+{(perf['random_mean'][idx]-perf['oracle_mean'][idx])/perf['random_mean'][idx]*_sage_const_100 :.1f}%改善)")

    # 2段階の肝: 方向が逆転する type
    reversed_cts = [(ct, info) for ct, info in model.items() if info["r"] > _sage_const_0p05 ]
    if reversed_cts:
        print(f"\n  ⚠ GlobalBurauと逆方向の cycle type:")
        for ct, info in sorted(reversed_cts, key=lambda x: -x[_sage_const_1 ]["r"]):
            print(f"    {ct}: r={info['r']:+.3f}  n={info['n']}  "
                  f"→ LOW Burau が良い（グローバルと逆）")

print(f"""
=================================================================
  W-7h 実験完了  出力先: {OUT}
=================================================================
""")

