

# This file was *autogenerated* from the file exp_W7-2a.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65 = Integer(65); _sage_const_42 = Integer(42); _sage_const_24 = Integer(24); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_4 = Integer(4); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_2 = Integer(2); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_25 = Integer(25); _sage_const_3p0 = RealNumber('3.0'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_0p85 = RealNumber('0.85'); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_45 = Integer(45); _sage_const_55 = Integer(55); _sage_const_0p001 = RealNumber('0.001'); _sage_const_0p01 = RealNumber('0.01'); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100); _sage_const_5000 = Integer(5000); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_0p0 = RealNumber('0.0'); _sage_const_28 = Integer(28); _sage_const_9 = Integer(9); _sage_const_48 = Integer(48); _sage_const_18 = Integer(18); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_0p15 = RealNumber('0.15'); _sage_const_8 = Integer(8); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p002 = RealNumber('0.002'); _sage_const_7 = Integer(7); _sage_const_0p27 = RealNumber('0.27'); _sage_const_1p25 = RealNumber('1.25'); _sage_const_120 = Integer(120); _sage_const_12 = Integer(12); _sage_const_30 = Integer(30); _sage_const_0p608 = RealNumber('0.608'); _sage_const_0p868 = RealNumber('0.868'); _sage_const_1p05 = RealNumber('1.05'); _sage_const_0p30 = RealNumber('0.30')#!/usr/bin/env sage
# exp_W7-2a.sage — W-7-2 Phase 1
# Burau(t) 複数評価点による多変量解析
# モデル: OLS (statsmodels) + LassoCV + RidgeCV
# 評価:  5-fold CV R²,  Precision@N,  VIF 診断,  Lasso 係数パス
#
# 比較ベースライン（W-7 シリーズ既知値）
#   GlobalBurau 単独: r=-0.5257, CV R²≈0.27, P@50≈0.608
#   3-Stage-25%:      P@50=0.868
#   SRM+GF_M30:       P@20=0.900, P@50=0.852

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from collections import defaultdict
from pathlib import Path
from sage.combinat.permutation import Permutation as SagePerm
from itertools import permutations as iter_perms

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LassoCV, RidgeCV, LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

try:
    import statsmodels.api as sm
    from statsmodels.stats.outliers_influence import variance_inflation_factor
    HAS_SM = True
except ImportError:
    print("  [警告] statsmodels 未インストール。OLS/VIF をスキップします。")
    print("         pip install statsmodels で追加可能。")
    HAS_SM = False

print("=" * _sage_const_65 )
print("  W-7-2a: Burau 多点評価 × 多変量回帰 (Phase 1)")
print("=" * _sage_const_65 )

OUT = Path("/mnt/c/Users/yoshi/don_theory/lab/wild/W07/results/W7-2a")
OUT.mkdir(parents=True, exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# 数値セットアップ（W-7 シリーズ共通 seed）
# ══════════════════════════════════════════════════════════════════
rng = np.random.default_rng(int(_sage_const_42 ))
d   = _sage_const_24 
A_dyn  = rng.standard_normal((d,d))*_sage_const_0p25 ;  A_dyn = A_dyn - A_dyn.T
b_bias = rng.standard_normal(d)*_sage_const_0p1 
a_vec  = np.zeros(d);  a_vec[:d//_sage_const_4 ] = _sage_const_1p0 
M_mat  = rng.standard_normal((d,d))*_sage_const_0p3 
M_mat  = M_mat / (np.linalg.norm(M_mat,_sage_const_2 )+_sage_const_1en8 )
bias_list = [rng.standard_normal(d)*(_sage_const_0p2 +_sage_const_0p05 *i) for i in range(_sage_const_4 )]
theta_star = np.array([_sage_const_1p0 , _sage_const_1p0 ])
p0_master  = rng.standard_normal(d)*_sage_const_0p5 
N_ROUNDS = _sage_const_2 ;  N_GRID = _sage_const_25 
th1 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)
th2 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)

def time_ev(p): return np.tanh(A_dyn@p+b_bias)*_sage_const_0p5 +p*_sage_const_0p4 
def make_ops(K):
    return [
        lambda p,th,_=None: p+th[_sage_const_0 ]*a_vec,
        lambda p,th,_=None: (np.eye(d)+th[_sage_const_1 ]*M_mat)@p,
        lambda p,th,_=None: np.tanh(p*_sage_const_1p2 )*_sage_const_0p9 ,
        lambda p,th,_=None: np.tanh(p*_sage_const_0p8 +bias_list[_sage_const_0 ])*_sage_const_0p7 ,
        lambda p,th,_=None: p*_sage_const_0p6 +np.tanh(bias_list[_sage_const_1 ])*_sage_const_0p4 ,
        lambda p,th,_=None: np.tanh(p+bias_list[_sage_const_2 ])*_sage_const_0p85 ,
    ][:K]

def compute_dist(order, K):
    ops = make_ops(K);  p0 = p0_master.copy()
    ref = list(range(K))
    def traj(ord_, th):
        p = p0.copy();  t = [p.copy()]
        for _ in range(N_ROUNDS):
            for idx in ord_:
                p = time_ev(p);  p = ops[idx](p,th);  t.append(p.copy())
        return np.array(t)
    zt = traj(ref, theta_star)
    def J(ord_, th): return float(np.mean(np.sum((traj(ord_,th)-zt)**_sage_const_2 ,axis=_sage_const_1 )))
    grid = np.array([[J(order,[th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    ref_g= np.array([[J(ref,  [th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    return float(np.sqrt(np.mean((grid.ravel()-ref_g.ravel())**_sage_const_2 )))

# ══════════════════════════════════════════════════════════════════
# Burau 評価点
# ══════════════════════════════════════════════════════════════════
T_FRACS = [(_sage_const_1 ,_sage_const_4 ), (_sage_const_1 ,_sage_const_3 ), (_sage_const_1 ,_sage_const_2 ), (_sage_const_2 ,_sage_const_3 ), (_sage_const_3 ,_sage_const_4 )]
T_LABELS = ["t=1/4", "t=1/3", "t=1/2", "t=2/3", "t=3/4"]

# ══════════════════════════════════════════════════════════════════
# データ構築: K=6, 全 720 置換
# ══════════════════════════════════════════════════════════════════
K = _sage_const_6 
print(f"\n[K={K}] 全 {factorial(K)} 件のデータ構築中...")
print(f"  Burau 評価点: {T_LABELS}")
BK = BraidGroup(K);  gK = list(BK.generators())

rows = []
for perm_iter in iter_perms(range(_sage_const_1 , K+_sage_const_1 )):
    sp    = SagePerm(list(perm_iter))
    b     = BK.one()
    for i in sp.reduced_word(): b = b * gK[i-_sage_const_1 ]

    # Burau 行列を一度シンボリックで取得してから各点で評価
    bm = b.burau_matrix()
    btr_vals = []
    for p, q in T_FRACS:
        btr_vals.append(float(bm(t=QQ(p)/QQ(q)).trace()))

    order = [x-_sage_const_1  for x in perm_iter]
    ct    = list(sp.cycle_type())
    dist  = compute_dist(order, K)

    rows.append({
        "label"   : "".join(str(x+_sage_const_1 ) for x in order),
        "order"   : order,
        "burau_v" : btr_vals,          # 5次元ベクトル
        "cayley"  : K - len(ct),
        "ct_str"  : str(ct),
        "dist"    : dist,
    })

n_rows = len(rows)
dists  = np.array([r["dist"] for r in rows])
print(f"  完了。dist: [{dists.min():.3f}, {dists.max():.3f}]  mean={dists.mean():.3f}")

# ══════════════════════════════════════════════════════════════════
# 特徴行列の組み立て
# ══════════════════════════════════════════════════════════════════
# Feature set A: Burau(1/2) のみ（ベースライン）
# Feature set B: Burau 全 5 点
# Feature set C: Burau 全 5 点 + Cayley 距離

X_A = np.array([[r["burau_v"][_sage_const_2 ]]        for r in rows])   # (720,1)
X_B = np.array([r["burau_v"]             for r in rows])   # (720,5)
X_C = np.array([r["burau_v"]+[r["cayley"]] for r in rows]) # (720,6)
y   = dists

feature_sets = {
    "A: Burau(1/2) のみ"          : (X_A, ["burau_1/2"]),
    "B: Burau 5点"                 : (X_B, T_LABELS),
    "C: Burau 5点 + Cayley"        : (X_C, T_LABELS + ["cayley"]),
}

# ══════════════════════════════════════════════════════════════════
# 5-fold CV 設定（W-7 シリーズ共通）
# ══════════════════════════════════════════════════════════════════
kf = KFold(n_splits=_sage_const_5 , shuffle=True, random_state=int(_sage_const_42 ))

# ══════════════════════════════════════════════════════════════════
# ① Pearson r（各評価点の単変量相関）
# ══════════════════════════════════════════════════════════════════
print("\n[① 各 Burau(t) 評価点の単変量 Pearson r]")
print(f"  {'評価点':<10}  {'r':>8}  {'p値':>12}  {'R²':>8}")
print("  " + "-"*_sage_const_45 )
for i, lbl in enumerate(T_LABELS):
    r_val, p_val = stats.pearsonr(X_B[:, i], y)
    print(f"  {lbl:<10}  {r_val:+8.4f}  {p_val:12.3e}  {r_val**_sage_const_2 :8.4f}")

# 評価点間の相関行列
print("\n[① Burau 評価点間の相関行列（多重共線性の確認）]")
corr_bv = np.corrcoef(X_B.T)
hdr = f"  {'':10}" + "".join(f"{l:>8}" for l in T_LABELS)
print(hdr)
for i, li in enumerate(T_LABELS):
    row_str = f"  {li:<10}" + "".join(f"{corr_bv[i,j]:8.3f}" for j in range(len(T_LABELS)))
    print(row_str)

# ══════════════════════════════════════════════════════════════════
# ② OLS 重回帰（statsmodels）
# ══════════════════════════════════════════════════════════════════
if HAS_SM:
    print("\n[② OLS 重回帰分析 (statsmodels)]")
    for name, (X, feat_names) in feature_sets.items():
        print(f"\n  ── {name} ──")
        X_sc  = StandardScaler().fit_transform(X)
        X_ols = sm.add_constant(X_sc)
        col_names = ["const"] + feat_names
        model = sm.OLS(y, X_ols).fit()

        # 係数テーブル
        print(f"  {'変数':<15}  {'係数':>9}  {'t値':>8}  {'p値':>10}  {'有意'}")
        print("  " + "-"*_sage_const_55 )
        for j, cname in enumerate(col_names):
            coef = model.params[j]
            tval = model.tvalues[j]
            pval = model.pvalues[j]
            sig  = "***" if pval<_sage_const_0p001  else ("**" if pval<_sage_const_0p01  else ("*" if pval<_sage_const_0p05  else ""))
            print(f"  {cname:<15}  {coef:9.4f}  {tval:8.3f}  {pval:10.4e}  {sig}")
        print(f"  R²={model.rsquared:.4f}  Adj.R²={model.rsquared_adj:.4f}"
              f"  F={model.fvalue:.2f}  F_p={model.f_pvalue:.3e}")

        # VIF（特徴量が 2 個以上のとき）
        if X.shape[_sage_const_1 ] >= _sage_const_2 :
            print(f"\n  [VIF 診断]")
            vifs = [variance_inflation_factor(X_sc, j) for j in range(X_sc.shape[_sage_const_1 ])]
            for fname, vif_val in zip(feat_names, vifs):
                flag = " ← 多重共線性の懸念" if vif_val > _sage_const_10  else ""
                print(f"    {fname:<12}: VIF={vif_val:.2f}{flag}")

# ══════════════════════════════════════════════════════════════════
# ③ 5-fold CV R²（LassoCV / RidgeCV / OLS）
# ══════════════════════════════════════════════════════════════════
print("\n[③ 5-fold CV R²]")
print(f"  {'特徴量セット':<28}  {'OLS':>7}  {'Ridge':>7}  {'Lasso':>7}")
print("  " + "-"*_sage_const_55 )

cv_r2_results = {}
for name, (X, feat_names) in feature_sets.items():
    pipe_ols   = Pipeline([("sc", StandardScaler()), ("m", LinearRegression())])
    pipe_ridge = Pipeline([("sc", StandardScaler()),
                           ("m", RidgeCV(alphas=[_sage_const_0p01 ,_sage_const_0p1 ,_sage_const_1 ,_sage_const_10 ,_sage_const_100 ], cv=kf))])
    pipe_lasso = Pipeline([("sc", StandardScaler()),
                           ("m", LassoCV(cv=kf, random_state=int(_sage_const_42 ), max_iter=_sage_const_5000 ))])

    r2_ols   = float(np.mean(cross_val_score(pipe_ols,   X, y, cv=kf, scoring="r2")))
    r2_ridge = float(np.mean(cross_val_score(pipe_ridge, X, y, cv=kf, scoring="r2")))
    r2_lasso = float(np.mean(cross_val_score(pipe_lasso, X, y, cv=kf, scoring="r2")))

    cv_r2_results[name] = {"ols": r2_ols, "ridge": r2_ridge, "lasso": r2_lasso}

    # ベースライン（A: Burau単独）との差分を表示
    tag = ""
    if name != "A: Burau(1/2) のみ":
        delta = r2_ridge - cv_r2_results["A: Burau(1/2) のみ"]["ridge"]
        tag = f"  (Δridge={delta:+.4f})"
    print(f"  {name:<28}  {r2_ols:7.4f}  {r2_ridge:7.4f}  {r2_lasso:7.4f}{tag}")

# ══════════════════════════════════════════════════════════════════
# ④ 5-fold CV Precision@N
# ══════════════════════════════════════════════════════════════════
N_vals = [_sage_const_10 , _sage_const_20 , _sage_const_50 , _sage_const_100 ]

def oracle_labels(rows_sub, N):
    N = int(min(N, len(rows_sub)))
    return {r["label"] for r in sorted(rows_sub, key=lambda r: r["dist"])[:N]}

def precision_at(sel, true):
    return float(len(sel & true)) / float(len(true)) if true else _sage_const_0p0 

# 各特徴量セットで RidgeCV の予測スコアによる Precision@N を計算
print("\n[④ 5-fold CV Precision@N (RidgeCV)]")
hdr = f"  {'特徴量セット':<28}|" + "".join(f"  @{N:<4}|" for N in N_vals)
print(hdr)
print("  " + "-"*(_sage_const_28  + _sage_const_9 *len(N_vals) + _sage_const_3 ))

prec_results = {}
for name, (X, feat_names) in feature_sets.items():
    prec_by_N = {N: [] for N in N_vals}
    for tr_idx, te_idx in kf.split(X):
        rows_te = [rows[i] for i in te_idx]
        sc      = StandardScaler().fit(X[tr_idx])
        X_tr_sc = sc.transform(X[tr_idx])
        X_te_sc = sc.transform(X[te_idx])
        reg     = RidgeCV(alphas=[_sage_const_0p01 ,_sage_const_0p1 ,_sage_const_1 ,_sage_const_10 ,_sage_const_100 ], cv=_sage_const_5 )
        reg.fit(X_tr_sc, y[tr_idx])
        y_pred  = reg.predict(X_te_sc)

        for N in N_vals:
            n       = int(min(N, len(rows_te)))
            true_top = oracle_labels(rows_te, n)
            ranked   = np.argsort(y_pred)[:n]
            sel      = {rows_te[i]["label"] for i in ranked}
            prec_by_N[N].append(precision_at(sel, true_top))

    prec_results[name] = {N: float(np.mean(v)) for N, v in prec_by_N.items()}
    line = f"  {name:<28}|" + "".join(f"  {prec_results[name][N]:.3f}|" for N in N_vals)
    print(line)

# 参考: W-7 ベースライン
print(f"\n  参考（W-7 既知値）:")
print(f"  {'GlobalBurau(1/2)':<28}|  0.600|  0.600|  0.608|  —   |")
print(f"  {'3-Stage-25%':<28}|  —    |  —    |  0.868|  —   |")
print(f"  {'SRM+GF_M30':<28}|  —    |  0.900|  0.852|  —   |")

# ══════════════════════════════════════════════════════════════════
# ⑤ Lasso 係数の安定性（fold 間の分散）
# ══════════════════════════════════════════════════════════════════
print("\n[⑤ Lasso 係数の安定性（Burau 5点モデル）]")
X_B_name = "B: Burau 5点"
X_B_data, B_feat_names = feature_sets[X_B_name]

lasso_coefs = []
for tr_idx, te_idx in kf.split(X_B_data):
    sc      = StandardScaler().fit(X_B_data[tr_idx])
    X_tr_sc = sc.transform(X_B_data[tr_idx])
    lasso   = LassoCV(cv=_sage_const_5 , random_state=int(_sage_const_42 ), max_iter=_sage_const_5000 )
    lasso.fit(X_tr_sc, y[tr_idx])
    lasso_coefs.append(lasso.coef_)

lasso_coefs = np.array(lasso_coefs)  # (5 folds, 5 features)
print(f"  {'特徴量':<12}  {'平均係数':>10}  {'±std':>8}  {'ゼロ化率'}")
print("  " + "-"*_sage_const_48 )
for j, fname in enumerate(B_feat_names):
    mean_c = float(lasso_coefs[:, j].mean())
    std_c  = float(lasso_coefs[:, j].std())
    zero_r = float((lasso_coefs[:, j] == _sage_const_0 ).mean())
    print(f"  {fname:<12}  {mean_c:10.4f}  {std_c:8.4f}  {zero_r:.1%}")

# ══════════════════════════════════════════════════════════════════
# 可視化
# ══════════════════════════════════════════════════════════════════
print("\n[可視化]")

fig, axes = plt.subplots(_sage_const_2 , _sage_const_3 , figsize=(_sage_const_18 , _sage_const_11 ))
fig.suptitle("W-7-2a: Burau Multi-point Evaluation — Multivariate Analysis (K=6)",
             fontsize=_sage_const_13 )

# ── 図1: 各評価点の散布図（dist vs Burau(t)）──────────────────
for i, (lbl, ax_) in enumerate(zip(T_LABELS, axes[_sage_const_0 ])):
    if i >= _sage_const_3 : break
    x_i = X_B[:, i]
    r_i, p_i = stats.pearsonr(x_i, dists)
    ax_.scatter(x_i, dists, alpha=_sage_const_0p15 , s=_sage_const_8 , color="steelblue")
    # 回帰線
    m, b_ = np.polyfit(x_i, dists, _sage_const_1 )
    xs = np.linspace(x_i.min(), x_i.max(), _sage_const_100 )
    ax_.plot(xs, m*xs+b_, "r-", lw=_sage_const_1p5 , alpha=_sage_const_0p8 )
    ax_.set_xlabel(f"Burau trace at {lbl}")
    ax_.set_ylabel("dist")
    ax_.set_title(f"{lbl}\nr={r_i:+.4f}, p={p_i:.2e}")
    ax_.grid(True, alpha=_sage_const_0p3 )

for i, (lbl, ax_) in enumerate(zip(T_LABELS[_sage_const_3 :], axes[_sage_const_1 ][:_sage_const_2 ])):
    x_i = X_B[:, _sage_const_3 +i]
    r_i, p_i = stats.pearsonr(x_i, dists)
    ax_.scatter(x_i, dists, alpha=_sage_const_0p15 , s=_sage_const_8 , color="steelblue")
    m, b_ = np.polyfit(x_i, dists, _sage_const_1 )
    xs = np.linspace(x_i.min(), x_i.max(), _sage_const_100 )
    ax_.plot(xs, m*xs+b_, "r-", lw=_sage_const_1p5 , alpha=_sage_const_0p8 )
    ax_.set_xlabel(f"Burau trace at {lbl}")
    ax_.set_ylabel("dist")
    ax_.set_title(f"{lbl}\nr={r_i:+.4f}, p={p_i:.2e}")
    ax_.grid(True, alpha=_sage_const_0p3 )

# ── 図2: CV R² 比較（特徴量セット × モデル）────────────────────
ax = axes[_sage_const_1 ][_sage_const_2 ]
model_labels = ["OLS", "Ridge", "Lasso"]
x_pos = np.arange(len(feature_sets))
width = _sage_const_0p25 
colors = ["#2196F3", "#4CAF50", "#FF9800"]
for k_m, (m_lbl, color) in enumerate(zip(model_labels, colors)):
    vals = [cv_r2_results[n][m_lbl.lower()] for n in feature_sets]
    ax.bar(x_pos + k_m*width, vals, width, label=m_lbl, color=color, alpha=_sage_const_0p8 )
    for xp, v in zip(x_pos + k_m*width, vals):
        ax.text(xp, v+_sage_const_0p002 , f"{v:.3f}", ha="center", fontsize=_sage_const_7 )
ax.axhline(_sage_const_0p27 , ls="--", color="red", alpha=_sage_const_0p6 , label="W-7 ceiling (R²=0.27)")
ax.set_xticks(x_pos + width)
ax.set_xticklabels(["A: Burau\n(1/2)only", "B: Burau\n5点",
                    "C: Burau5点\n+Cayley"], fontsize=_sage_const_9 )
ax.set_ylabel("5-fold CV R²")
ax.set_title("CV R² by Feature Set")
ax.legend(fontsize=_sage_const_8 ); ax.grid(True, alpha=_sage_const_0p3 , axis="y")
ax.set_ylim(_sage_const_0 , max(v["ridge"] for v in cv_r2_results.values())*_sage_const_1p25  + _sage_const_0p05 )

plt.tight_layout()
fig.savefig(OUT / "W7-2a_fig1_scatter_r2.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig1 saved")

# ── 図3: Lasso 係数の fold 間安定性（ヒートマップ）────────────
fig, axes = plt.subplots(_sage_const_1 , _sage_const_2 , figsize=(_sage_const_13 , _sage_const_5 ))
fig.suptitle("W-7-2a: Lasso Coefficient Stability across CV Folds (Feature Set B)", fontsize=_sage_const_12 )

ax = axes[_sage_const_0 ]
im = ax.imshow(lasso_coefs, aspect="auto", cmap="RdBu_r",
               vmin=-np.abs(lasso_coefs).max(), vmax=np.abs(lasso_coefs).max())
ax.set_xticks(range(len(B_feat_names)))
ax.set_xticklabels(B_feat_names, rotation=_sage_const_30 , ha="right", fontsize=_sage_const_9 )
ax.set_yticks(range(_sage_const_5 ))
ax.set_yticklabels([f"fold {i+_sage_const_1 }" for i in range(_sage_const_5 )])
ax.set_title("Lasso Coefficients (standardized features)")
plt.colorbar(im, ax=ax)
for i in range(_sage_const_5 ):
    for j in range(len(B_feat_names)):
        ax.text(j, i, f"{lasso_coefs[i,j]:.2f}", ha="center", va="center",
                fontsize=_sage_const_8 , color="black")

ax = axes[_sage_const_1 ]
mean_c = lasso_coefs.mean(axis=_sage_const_0 )
std_c  = lasso_coefs.std(axis=_sage_const_0 )
colors_bar = ["#F44336" if abs(m)>_sage_const_0p01  else "#BDBDBD" for m in mean_c]
ax.bar(range(len(B_feat_names)), mean_c, yerr=std_c, capsize=_sage_const_5 ,
       color=colors_bar, alpha=_sage_const_0p85 )
ax.axhline(_sage_const_0 , color="black", lw=_sage_const_0p8 )
ax.set_xticks(range(len(B_feat_names)))
ax.set_xticklabels(B_feat_names, rotation=_sage_const_30 , ha="right", fontsize=_sage_const_9 )
ax.set_ylabel("Mean Lasso coefficient (±std)")
ax.set_title("Feature Importance: Mean ± Std across Folds\n(gray = collapsed to 0)")
ax.grid(True, alpha=_sage_const_0p3 , axis="y")

plt.tight_layout()
fig.savefig(OUT / "W7-2a_fig2_lasso_stability.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig2 saved")

# ── 図4: Precision@N カーブ（特徴量セット比較）──────────────────
fig, ax = plt.subplots(figsize=(_sage_const_9 , _sage_const_6 ))
fig.suptitle("W-7-2a: Precision@N by Feature Set (5-fold CV, RidgeCV)", fontsize=_sage_const_12 )
colors_fs = {"A: Burau(1/2) のみ": "blue",
             "B: Burau 5点":       "red",
             "C: Burau 5点 + Cayley": "green"}
markers_fs = {"A: Burau(1/2) のみ": "o",
              "B: Burau 5点":       "s",
              "C: Burau 5点 + Cayley": "^"}
for name in feature_sets:
    vals = [prec_results[name][N] for N in N_vals]
    ax.plot(N_vals, vals, marker=markers_fs[name], color=colors_fs[name],
            lw=_sage_const_2 , label=name, alpha=_sage_const_0p9 )
# W-7 参考ライン
ax.axhline(_sage_const_0p608 , ls="--", color="blue",  alpha=_sage_const_0p4 , lw=_sage_const_1p2 , label="W-7 GlobalBurau P@50=0.608")
ax.axhline(_sage_const_0p868 , ls="--", color="green", alpha=_sage_const_0p4 , lw=_sage_const_1p2 , label="W-7 3-Stage-25% P@50=0.868")
ax.set_xlabel("N (selected)"); ax.set_ylabel("Precision@N")
ax.set_title("Precision@N comparison")
ax.legend(fontsize=_sage_const_9 ); ax.grid(True, alpha=_sage_const_0p3 ); ax.set_ylim(_sage_const_0 , _sage_const_1p05 )
plt.tight_layout()
fig.savefig(OUT / "W7-2a_fig3_precision.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig3 saved")

# ══════════════════════════════════════════════════════════════════
# 総合サマリー
# ══════════════════════════════════════════════════════════════════
print("\n" + "=" * _sage_const_65 )
print("  W-7-2a 総合サマリー")
print("=" * _sage_const_65 )

ref_r2  = cv_r2_results["A: Burau(1/2) のみ"]["ridge"]
best_r2 = max(v["ridge"] for v in cv_r2_results.values())
best_fs = max(cv_r2_results, key=lambda k: cv_r2_results[k]["ridge"])

print(f"\n  ベースライン（Burau 1点 Ridge）: CV R²={ref_r2:.4f}")
print(f"  最良（{best_fs}）: CV R²={best_r2:.4f}")
delta_r2 = best_r2 - ref_r2
if delta_r2 > _sage_const_0p01 :
    print(f"  → R² が +{delta_r2:.4f} 改善 ★ Burau 複数評価点に情報量あり")
elif delta_r2 > _sage_const_0p002 :
    print(f"  → R² が +{delta_r2:.4f} わずかに改善（誤差範囲の可能性）")
else:
    print(f"  → R² の変化 {delta_r2:+.4f}  ≒ 変化なし")
    print(f"    → Burau(1/2) の単点評価で既に情報量を使い切っている可能性")
    print(f"    → 次は Phase 2（固有値スペクトル）または LKB へ進む価値あり")

print(f"\n  W-7 天井（CV R²≈0.27）との比較:")
print(f"    最良 CV R²={best_r2:.4f}  天井={_sage_const_0p27 :.4f}  差={best_r2-_sage_const_0p27 :+.4f}")

print(f"\n  Precision@50 比較:")
best_p50 = max(prec_results[n][_sage_const_50 ] for n in feature_sets)
best_p50_fs = max(feature_sets, key=lambda n: prec_results[n][_sage_const_50 ])
print(f"    最良: {best_p50_fs} → P@50={best_p50:.4f}")
print(f"    3-Stage-25% 参考値:               P@50=0.8680")
print(f"    差: {best_p50-_sage_const_0p868 :+.4f}")

print(f"\n  次のステップ:")
if best_r2 > _sage_const_0p30 :
    print(f"  → Phase 2 へ：固有値スペクトルでさらに掘る価値あり")
else:
    print(f"  → Phase 2 へ：Burau 固有値スペクトル（trace より豊富）を試す")
    print(f"     または Phase 3 へ：LKB 忠実表現（非忠実性が天井の原因かの判定）")

print(f"\n  出力先: {OUT}")
print("=" * _sage_const_65 )

