

# This file was *autogenerated* from the file exp_W7k.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65 = Integer(65); _sage_const_42 = Integer(42); _sage_const_24 = Integer(24); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_4 = Integer(4); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_2 = Integer(2); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_25 = Integer(25); _sage_const_3p0 = RealNumber('3.0'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_0p85 = RealNumber('0.85'); _sage_const_6 = Integer(6); _sage_const_100 = Integer(100); _sage_const_1p5 = RealNumber('1.5'); _sage_const_3 = Integer(3); _sage_const_0p0 = RealNumber('0.0'); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_150 = Integer(150); _sage_const_5 = Integer(5); _sage_const_40 = Integer(40); _sage_const_30 = Integer(30); _sage_const_60 = Integer(60); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p8 = RealNumber('1.8'); _sage_const_1p05 = RealNumber('1.05'); _sage_const_120 = Integer(120); _sage_const_35 = Integer(35); _sage_const_0p01 = RealNumber('0.01'); _sage_const_6p5 = RealNumber('6.5'); _sage_const_0p02 = RealNumber('0.02'); _sage_const_4p0 = RealNumber('4.0'); _sage_const_9p0 = RealNumber('9.0'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0p97 = RealNumber('0.97')#!/usr/bin/env sage
# exp_W7k.sage — ベイズ系モデル追加比較
# GaussianNB (分類) / BayesianRidge / ARD Regression / Gaussian Process
# W-7j の結果に合流させる形で Precision@N を比較

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from collections import defaultdict
from pathlib import Path
from sage.combinat.permutation import Permutation as SagePerm
from itertools import permutations as iter_perms
import copy

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import BayesianRidge, ARDRegression
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel, Matern
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, cross_val_score
import xgboost as xgb

print("=" * _sage_const_65 )
print("  W-7k: ベイズ系モデル vs 解析的スクリーニング")
print("  GaussianNB / BayesianRidge / ARD / GaussianProcess")
print("=" * _sage_const_65 )

OUT = Path("/mnt/c/Users/yoshi/don_theory/lab/wild/results/W7k")
OUT.mkdir(parents=True, exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# 数値セットアップ（同一 seed）
# ══════════════════════════════════════════════════════════════════
rng = np.random.default_rng(int(_sage_const_42 ))
d   = _sage_const_24 
A_dyn  = rng.standard_normal((d,d))*_sage_const_0p25 ;  A_dyn = A_dyn - A_dyn.T
b_bias = rng.standard_normal(d)*_sage_const_0p1 
a_vec  = np.zeros(d);  a_vec[:d//_sage_const_4 ] = _sage_const_1p0 
M_mat  = rng.standard_normal((d,d))*_sage_const_0p3 
M_mat  = M_mat / (np.linalg.norm(M_mat,_sage_const_2 )+_sage_const_1en8 )
bias_list = [rng.standard_normal(d)*(_sage_const_0p2 +_sage_const_0p05 *i) for i in range(_sage_const_4 )]
theta_star = np.array([_sage_const_1p0 , _sage_const_1p0 ])
p0_master  = rng.standard_normal(d)*_sage_const_0p5 
N_ROUNDS = _sage_const_2 ;  N_GRID = _sage_const_25 
th1 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)
th2 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)

def time_ev(p): return np.tanh(A_dyn@p+b_bias)*_sage_const_0p5 +p*_sage_const_0p4 
def make_ops(K):
    return [
        lambda p,th,_=None: p+th[_sage_const_0 ]*a_vec,
        lambda p,th,_=None: (np.eye(d)+th[_sage_const_1 ]*M_mat)@p,
        lambda p,th,_=None: np.tanh(p*_sage_const_1p2 )*_sage_const_0p9 ,
        lambda p,th,_=None: np.tanh(p*_sage_const_0p8 +bias_list[_sage_const_0 ])*_sage_const_0p7 ,
        lambda p,th,_=None: p*_sage_const_0p6 +np.tanh(bias_list[_sage_const_1 ])*_sage_const_0p4 ,
        lambda p,th,_=None: np.tanh(p+bias_list[_sage_const_2 ])*_sage_const_0p85 ,
    ][:K]

def compute_dist(order, K):
    ops = make_ops(K);  p0 = p0_master.copy()
    ref = list(range(K))
    def traj(ord_, th):
        p = p0.copy();  t = [p.copy()]
        for _ in range(N_ROUNDS):
            for idx in ord_:
                p = time_ev(p);  p = ops[idx](p,th);  t.append(p.copy())
        return np.array(t)
    zt = traj(ref, theta_star)
    def J(ord_, th): return float(np.mean(np.sum((traj(ord_,th)-zt)**_sage_const_2 ,axis=_sage_const_1 )))
    grid = np.array([[J(order,[th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    ref_g= np.array([[J(ref,  [th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    return float(np.sqrt(np.mean((grid.ravel()-ref_g.ravel())**_sage_const_2 )))

# ══════════════════════════════════════════════════════════════════
# データ構築: K=6
# ══════════════════════════════════════════════════════════════════
K = _sage_const_6 
print(f"\n[K={K}] 全 {factorial(K)} 件のデータ構築中...")
BK = BraidGroup(K);  gK = list(BK.generators())
rows = []
for perm in iter_perms(range(_sage_const_1 , K+_sage_const_1 )):
    sp   = SagePerm(list(perm))
    b    = BK.one()
    for i in sp.reduced_word(): b = b * gK[i-_sage_const_1 ]
    btr  = float(b.burau_matrix()(t=QQ(_sage_const_1 )/QQ(_sage_const_2 )).trace())
    ct   = list(sp.cycle_type())
    dist = compute_dist([x-_sage_const_1  for x in perm], K)
    rows.append({
        "label"         : "".join(str(x) for x in perm),
        "burau"         : btr,
        "writhe"        : len(sp.reduced_word()),
        "max_cycle_len" : int(max(ct)),
        "n_cycles"      : len(ct),
        "n_fixed"       : int(ct.count(_sage_const_1 )),
        "ct_str"        : str(ct),
        "dist"          : dist,
    })
dists = np.array([r["dist"] for r in rows])
print(f"  完了。dist: [{dists.min():.3f}, {dists.max():.3f}]  mean={dists.mean():.3f}")

FEATURE_NAMES = ["burau", "writhe", "max_cycle_len", "n_cycles", "n_fixed"]
X_raw = np.array([[r[f] for f in FEATURE_NAMES] for r in rows])
y_reg = dists  # 回帰用: 連続値

# 分類用ラベル: 下位 25th percentile = 1 (良い順序), それ以外 = 0
thr25 = float(np.percentile(y_reg, _sage_const_25 ))
y_cls = (y_reg <= thr25).astype(int)
print(f"  分類ラベル: top-25% threshold={thr25:.3f}  "
      f"positive={y_cls.sum()}件 ({y_cls.mean()*_sage_const_100 :.0f}%)")

scaler = StandardScaler()
X = scaler.fit_transform(X_raw)

# ══════════════════════════════════════════════════════════════════
# ベイズ系モデル定義
# ══════════════════════════════════════════════════════════════════
kernel_rbf    = _sage_const_1p0  * RBF(length_scale=_sage_const_1p0 ) + WhiteKernel(noise_level=_sage_const_0p5 )
kernel_matern = _sage_const_1p0  * Matern(length_scale=_sage_const_1p0 , nu=_sage_const_1p5 ) + WhiteKernel(noise_level=_sage_const_0p5 )

BAYES_MODELS = {
    # 分類系（確率でランキング）
    "GaussianNB"    : ("cls", GaussianNB()),
    # 回帰系
    "BayesianRidge" : ("reg", BayesianRidge()),
    "ARD"           : ("reg", ARDRegression()),
    "GP-RBF"        : ("reg", GaussianProcessRegressor(kernel=kernel_rbf,
                                                        random_state=int(_sage_const_0 ),
                                                        normalize_y=True)),
    "GP-Matern"     : ("reg", GaussianProcessRegressor(kernel=kernel_matern,
                                                        random_state=int(_sage_const_0 ),
                                                        normalize_y=True)),
}

# W-7j の比較モデル（再掲用）
PREV_MODELS = {
    "SVR-RBF"  : ("reg", SVR()),
    "RF"       : ("reg", RandomForestRegressor(random_state=int(_sage_const_0 ))),
    "GBM"      : ("reg", GradientBoostingRegressor(random_state=int(_sage_const_0 ))),
    "XGBoost"  : ("reg", xgb.XGBRegressor(random_state=int(_sage_const_0 ), verbosity=int(_sage_const_0 ))),
}

ALL_MODELS = {**BAYES_MODELS, **PREV_MODELS}

# ══════════════════════════════════════════════════════════════════
# ユーティリティ: Precision@N
# ══════════════════════════════════════════════════════════════════
def oracle_top_labels(rows_subset, N):
    N = int(min(N, len(rows_subset)))
    return {r["label"] for r in sorted(rows_subset, key=lambda r: r["dist"])[:N]}

def precision_at(sel_labels, true_labels):
    return float(len(sel_labels & true_labels)) / float(len(true_labels))

def global_burau_labels(rows_subset, N):
    N = int(min(N, len(rows_subset)))
    bv = np.array([r["burau"] for r in rows_subset])
    dv = np.array([r["dist"]  for r in rows_subset])
    direction = -_sage_const_1  if stats.pearsonr(bv, dv)[_sage_const_0 ] > _sage_const_0  else +_sage_const_1 
    sel = sorted(rows_subset, key=lambda r: direction * r["burau"], reverse=True)[:N]
    return {r["label"] for r in sel}

def threestage_labels(rows_subset, N):
    """W-7i の 3-Stage-25% をサブセットに適用"""
    N = int(min(N, len(rows_subset)))
    all_d = np.array([r["dist"] for r in rows_subset])
    dist_thr = float(np.percentile(all_d, _sage_const_25 ))
    ct_mean = defaultdict(list)
    for r in rows_subset: ct_mean[r["ct_str"]].append(r["dist"])
    kept_cts = {ct for ct, dv in ct_mean.items() if float(np.mean(dv)) <= dist_thr}
    if not kept_cts:
        kept_cts = set(ct_mean.keys())
    kept = [r for r in rows_subset if r["ct_str"] in kept_cts]
    ct_grp = defaultdict(list)
    for r in kept: ct_grp[r["ct_str"]].append(r)
    selected = []
    for ct, grp in ct_grp.items():
        bv = np.array([r["burau"] for r in grp])
        dv = np.array([r["dist"]  for r in grp])
        rr = stats.pearsonr(bv, dv)[_sage_const_0 ] if len(grp) >= _sage_const_3  else _sage_const_0p0 
        direction = -_sage_const_1  if rr > _sage_const_0  else +_sage_const_1 
        n_sel = int(max(_sage_const_1 , round(N * len(grp) / len(kept))))
        ranked = sorted(grp, key=lambda r: direction * r["burau"], reverse=True)
        selected.extend(ranked[:n_sel])
    if len(selected) > N:
        selected = sorted(selected, key=lambda r: r["dist"])[:N]
    elif len(selected) < N:
        sel_lbl = {r["label"] for r in selected}
        rem = sorted([r for r in rows_subset if r["label"] not in sel_lbl],
                     key=lambda r: r["dist"])
        selected.extend(rem[:N - len(selected)])
    return {r["label"] for r in selected[:N]}

# ══════════════════════════════════════════════════════════════════
# 5-fold CV: Precision@N
# ══════════════════════════════════════════════════════════════════
print("\n[5-fold CV: Precision@N]")
N_vals = [_sage_const_10 , _sage_const_20 , _sage_const_50 , _sage_const_100 , _sage_const_150 ]
kf = KFold(n_splits=_sage_const_5 , shuffle=True, random_state=int(_sage_const_42 ))

cv_prec = {name: {N: [] for N in N_vals} for name in ALL_MODELS}
cv_prec["GlobalBurau"] = {N: [] for N in N_vals}
cv_prec["3Stg-25%"]    = {N: [] for N in N_vals}

labels_all = [r["label"] for r in rows]

print("  進捗: ", end="", flush=True)
for fold_idx, (train_idx, test_idx) in enumerate(kf.split(X)):
    print(f"fold{fold_idx+_sage_const_1 } ", end="", flush=True)
    X_tr, X_te = X[train_idx], X[test_idx]
    y_reg_tr, y_reg_te = y_reg[train_idx], y_reg[test_idx]
    y_cls_tr = y_cls[train_idx]
    rows_te = [rows[i] for i in test_idx]

    for N in N_vals:
        n = int(min(N, len(rows_te)))
        true_top = oracle_top_labels(rows_te, n)

        # 解析的ベースライン
        cv_prec["GlobalBurau"][N].append(
            precision_at(global_burau_labels(rows_te, n), true_top))
        cv_prec["3Stg-25%"][N].append(
            precision_at(threestage_labels(rows_te, n), true_top))

        # 各モデル
        for name, (task, base_model) in ALL_MODELS.items():
            m = copy.deepcopy(base_model)
            if task == "cls":
                m.fit(X_tr, y_cls_tr)
                # P(クラス=1=良い順序) が高い順に選ぶ
                proba = m.predict_proba(X_te)[:, _sage_const_1 ]
                top_idx = np.argsort(-proba)[:n]
            else:
                m.fit(X_tr, y_reg_tr)
                y_pred = m.predict(X_te)
                top_idx = np.argsort(y_pred)[:n]   # dist小さい順
            ml_top = {rows_te[i]["label"] for i in top_idx}
            cv_prec[name][N].append(precision_at(ml_top, true_top))
print("完了")

# ══════════════════════════════════════════════════════════════════
# 5-fold CV: R² / AUC（回帰 / 分類精度）
# ══════════════════════════════════════════════════════════════════
print("\n[5-fold CV: 予測精度]")
from sklearn.linear_model import LinearRegression
from sklearn.metrics import roc_auc_score

r2_results  = {}
auc_results = {}
kf2 = KFold(n_splits=_sage_const_5 , shuffle=True, random_state=int(_sage_const_42 ))

# 線形 Burau ベースライン
lr_r2 = cross_val_score(LinearRegression(), X[:,[_sage_const_0 ]], y_reg, cv=kf2, scoring="r2")
r2_results["Linear(Burau)"] = (float(lr_r2.mean()), float(lr_r2.std()))

for name, (task, base_model) in ALL_MODELS.items():
    if task == "reg":
        r2 = cross_val_score(copy.deepcopy(base_model), X, y_reg, cv=kf2, scoring="r2")
        r2_results[name] = (float(r2.mean()), float(r2.std()))
    else:
        # 分類: AUC
        aucs = []
        for tr_idx, te_idx in kf2.split(X):
            m = copy.deepcopy(base_model)
            m.fit(X[tr_idx], y_cls[tr_idx])
            proba = m.predict_proba(X[te_idx])[:, _sage_const_1 ]
            aucs.append(roc_auc_score(y_cls[te_idx], proba))
        auc_results[name] = (float(np.mean(aucs)), float(np.std(aucs)))

print(f"\n  回帰 R² (dist 予測):")
print(f"  {'モデル':<16} | R² mean±std")
print("  " + "-"*_sage_const_40 )
for name, (mean, std) in sorted(r2_results.items(), key=lambda x: -x[_sage_const_1 ][_sage_const_0 ]):
    bar = "█" * int(max(_sage_const_0 , mean) * _sage_const_30 )
    tag = " ← Burau単体ベースライン" if name == "Linear(Burau)" else ""
    print(f"  {name:<16} | {mean:+.4f}±{std:.4f}  {bar}{tag}")

print(f"\n  分類 AUC (上位25%識別):")
print(f"  {'モデル':<16} | AUC mean±std")
print("  " + "-"*_sage_const_40 )
for name, (mean, std) in sorted(auc_results.items(), key=lambda x: -x[_sage_const_1 ][_sage_const_0 ]):
    bar = "█" * int(max(_sage_const_0 , (mean-_sage_const_0p5 )*_sage_const_60 ))
    print(f"  {name:<16} | {mean:.4f}±{std:.4f}  {bar}")

# ══════════════════════════════════════════════════════════════════
# BayesianRidge / ARD の係数（特徴量への重み）
# ══════════════════════════════════════════════════════════════════
print("\n[BayesianRidge / ARD 係数（全データ学習）]")
for name in ["BayesianRidge", "ARD"]:
    m = copy.deepcopy(ALL_MODELS[name][_sage_const_1 ])
    m.fit(X, y_reg)
    print(f"\n  {name}:")
    for fn, coef in sorted(zip(FEATURE_NAMES, m.coef_), key=lambda x: -abs(x[_sage_const_1 ])):
        bar = "█" * int(abs(coef) * _sage_const_8 )
        sign = "+" if coef >= _sage_const_0  else "-"
        print(f"    {fn:<16}: {sign}{abs(coef):.4f}  {bar}")

# GP の学習済みカーネルパラメータ
print(f"\n[Gaussian Process 学習済みカーネル（全データ）]")
for name in ["GP-RBF", "GP-Matern"]:
    m = copy.deepcopy(ALL_MODELS[name][_sage_const_1 ])
    m.fit(X, y_reg)
    print(f"  {name}: {m.kernel_}")

# ══════════════════════════════════════════════════════════════════
# 全モデル Precision@N 結果表示
# ══════════════════════════════════════════════════════════════════
print("\n[全モデル Precision@N 比較（5-fold CV mean±std）]")

ALL_KEYS = (["GlobalBurau", "3Stg-25%"]
            + list(BAYES_MODELS.keys())
            + list(PREV_MODELS.keys()))

SECTIONS = [
    ("── 解析的", ["GlobalBurau", "3Stg-25%"]),
    ("── ベイズ系", list(BAYES_MODELS.keys())),
    ("── 従来ML (W-7j 再掲)", list(PREV_MODELS.keys())),
]

for section_title, keys in SECTIONS:
    print(f"\n  {section_title}")
    hdr = f"  {'手法':<16}|"
    for N in N_vals: hdr += f" @{N:<5}|"
    print(hdr)
    print("  " + "-"*(_sage_const_16  + _sage_const_9 *len(N_vals) + _sage_const_2 ))
    for key in keys:
        line = f"  {key:<16}|"
        for N in N_vals:
            vals = cv_prec[key][N]
            line += f" {np.mean(vals):.3f} |"
        print(line)

# ══════════════════════════════════════════════════════════════════
# 可視化
# ══════════════════════════════════════════════════════════════════
print("\n[可視化]")

# ── 図1: Precision@N カーブ（全モデル）──────────────────────────
fig, axes = plt.subplots(_sage_const_1 , _sage_const_2 , figsize=(_sage_const_16 , _sage_const_6 ))
fig.suptitle("W-7k: Precision@N — Bayesian Models vs Analytical (5-fold CV)", fontsize=_sage_const_12 )

styles = {
    "GlobalBurau" : ("blue",    "o",  "--", _sage_const_2p5 ),
    "3Stg-25%"    : ("green",   "s",  "-",  _sage_const_2p5 ),
    "GaussianNB"  : ("magenta", "^",  "-",  _sage_const_1p8 ),
    "BayesianRidge":("purple",  "D",  "-",  _sage_const_1p8 ),
    "ARD"         : ("indigo",  "v",  "-",  _sage_const_1p8 ),
    "GP-RBF"      : ("crimson", "P",  "-",  _sage_const_1p8 ),
    "GP-Matern"   : ("darkorange","h", "-", _sage_const_1p8 ),
    "SVR-RBF"     : ("#888",    "x",  ":",  _sage_const_1p2 ),
    "RF"          : ("#aaa",    "+",  ":",  _sage_const_1p2 ),
    "GBM"         : ("#ccc",    "1",  ":",  _sage_const_1p2 ),
    "XGBoost"     : ("#bbb",    "2",  ":",  _sage_const_1p2 ),
}

# 左: ベイズ系 + 解析的のみ
ax = axes[_sage_const_0 ]
focus_keys = ["GlobalBurau","3Stg-25%","GaussianNB","BayesianRidge","ARD","GP-RBF","GP-Matern"]
for key in focus_keys:
    c, mk, ls, lw = styles[key]
    means = [np.mean(cv_prec[key][N]) for N in N_vals]
    stds  = [np.std(cv_prec[key][N])  for N in N_vals]
    ax.plot(N_vals, means, marker=mk, ls=ls, color=c, lw=lw, label=key, alpha=_sage_const_0p9 )
    ax.fill_between(N_vals, [m-s for m,s in zip(means,stds)],
                    [m+s for m,s in zip(means,stds)], color=c, alpha=_sage_const_0p1 )
ax.set_xlabel("N (selected out of 720)")
ax.set_ylabel("Precision@N")
ax.set_title("Focus: Bayesian vs Analytical")
ax.legend(fontsize=_sage_const_9 )
ax.grid(True, alpha=_sage_const_0p3 )
ax.set_ylim(_sage_const_0 , _sage_const_1p05 )

# 右: 全モデル
ax = axes[_sage_const_1 ]
for key in ALL_KEYS:
    c, mk, ls, lw = styles[key]
    means = [np.mean(cv_prec[key][N]) for N in N_vals]
    ax.plot(N_vals, means, marker=mk, ls=ls, color=c, lw=lw, label=key, alpha=_sage_const_0p85 )
ax.set_xlabel("N (selected out of 720)")
ax.set_ylabel("Precision@N")
ax.set_title("All Models")
ax.legend(fontsize=_sage_const_8 , ncol=_sage_const_2 )
ax.grid(True, alpha=_sage_const_0p3 )
ax.set_ylim(_sage_const_0 , _sage_const_1p05 )

plt.tight_layout()
fig.savefig(OUT / "W7k_fig1_precision_all.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig1 saved: {OUT / 'W7k_fig1_precision_all.png'}")

# ── 図2: N=50 Precision@N バーチャート (全モデル横断)────────────
fig, ax = plt.subplots(figsize=(_sage_const_12 , _sage_const_5 ))
N_bar = _sage_const_50 
bar_keys   = ALL_KEYS
bar_values = [float(np.mean(cv_prec[k][N_bar])) for k in bar_keys]
bar_errs   = [float(np.std(cv_prec[k][N_bar]))  for k in bar_keys]
bar_colors = (["#2196F3","#4CAF50"]
              + ["#9C27B0","#673AB7","#3F51B5","#E91E63","#FF5722"]
              + ["#9E9E9E"]*_sage_const_4 )
bars = ax.bar(range(len(bar_keys)), bar_values, color=bar_colors,
              yerr=bar_errs, capsize=_sage_const_4 , alpha=_sage_const_0p85 )
ax.set_xticks(range(len(bar_keys)))
ax.set_xticklabels(bar_keys, rotation=_sage_const_35 , ha='right', fontsize=_sage_const_10 )
ax.set_ylabel("Precision@50 (5-fold CV)")
ax.set_title(f"W-7k: Precision@{N_bar} — 全モデル比較 (K=6, n=720)")
ax.axhline(float(np.mean(cv_prec["GlobalBurau"][N_bar])), ls="--", color="#2196F3",
           alpha=_sage_const_0p6 , label="GlobalBurau baseline")
for i, v in enumerate(bar_values):
    ax.text(i, v + _sage_const_0p01 , f"{v:.3f}", ha='center', fontsize=_sage_const_8 )

# 区切り線
ax.axvline(_sage_const_1p5 , color='gray', ls=':', alpha=_sage_const_0p5 )
ax.axvline(_sage_const_6p5 , color='gray', ls=':', alpha=_sage_const_0p5 )
ax.text(_sage_const_0p5 ,  _sage_const_0p02 , "解析的", ha='center', transform=ax.get_xaxis_transform(),
        fontsize=_sage_const_8 , color='gray')
ax.text(_sage_const_4p0 ,  _sage_const_0p02 , "ベイズ系", ha='center', transform=ax.get_xaxis_transform(),
        fontsize=_sage_const_8 , color='purple')
ax.text(_sage_const_9p0 ,  _sage_const_0p02 , "従来ML", ha='center', transform=ax.get_xaxis_transform(),
        fontsize=_sage_const_8 , color='gray')
ax.legend(fontsize=_sage_const_9 )
ax.set_ylim(_sage_const_0 , _sage_const_1p1 )
plt.tight_layout()
fig.savefig(OUT / "W7k_fig2_bar_N50.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig2 saved: {OUT / 'W7k_fig2_bar_N50.png'}")

# ── 図3: BayesianRidge 係数 vs ARD 係数（事後スパース性の比較）──
fig, axes = plt.subplots(_sage_const_1 , _sage_const_2 , figsize=(_sage_const_12 , _sage_const_4 ))
fig.suptitle("W-7k: Bayesian Linear Models — Coefficient Comparison", fontsize=_sage_const_12 )

for ax, name in zip(axes, ["BayesianRidge", "ARD"]):
    m = copy.deepcopy(ALL_MODELS[name][_sage_const_1 ])
    m.fit(X, y_reg)
    coefs = m.coef_
    order = np.argsort(np.abs(coefs))[::-_sage_const_1 ]
    colors_feat = []
    for fn in [FEATURE_NAMES[i] for i in order]:
        if fn in ("max_cycle_len","n_cycles","n_fixed"):
            colors_feat.append("#4CAF50")
        elif fn == "burau":
            colors_feat.append("#2196F3")
        else:
            colors_feat.append("#FF9800")
    ax.barh(range(len(FEATURE_NAMES)), [coefs[i] for i in order],
            color=colors_feat, alpha=_sage_const_0p85 )
    ax.set_yticks(range(len(FEATURE_NAMES)))
    ax.set_yticklabels([FEATURE_NAMES[i] for i in order])
    ax.set_xlabel("Coefficient (standardized)")
    ax.set_title(name)
    ax.axvline(_sage_const_0 , color='black', lw=_sage_const_0p8 )
    r2_m, r2_s = r2_results.get(name, (_sage_const_0 ,_sage_const_0 ))
    ax.text(_sage_const_0p97 , _sage_const_0p05 , f"CV R²={r2_m:.3f}±{r2_s:.3f}",
            transform=ax.transAxes, ha='right', fontsize=_sage_const_9 )

from matplotlib.patches import Patch
legend_elems = [Patch(facecolor="#4CAF50", label="cycle type 系"),
                Patch(facecolor="#2196F3", label="Burau trace"),
                Patch(facecolor="#FF9800", label="Writhe")]
axes[_sage_const_1 ].legend(handles=legend_elems, loc="lower right", fontsize=_sage_const_9 )
plt.tight_layout()
fig.savefig(OUT / "W7k_fig3_bayes_coefs.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig3 saved: {OUT / 'W7k_fig3_bayes_coefs.png'}")

# ══════════════════════════════════════════════════════════════════
# 総合サマリー
# ══════════════════════════════════════════════════════════════════
print("\n" + "=" * _sage_const_65 )
print("  総合サマリー")
print("=" * _sage_const_65 )

ref_n = _sage_const_50 
print(f"\n  [Precision@{ref_n} ランキング（全モデル）]")
ranking = sorted(
    [(k, float(np.mean(cv_prec[k][ref_n]))) for k in ALL_KEYS + ["3Stg-25%"]],
    key=lambda x: -x[_sage_const_1 ])
for rank, (key, val) in enumerate(ranking, _sage_const_1 ):
    bar = "█" * int(val * _sage_const_30 )
    tag = " ← 解析的" if key in ("GlobalBurau","3Stg-25%") else ""
    tag += " ← ベイズ系" if key in BAYES_MODELS else ""
    print(f"  {rank:2}. {key:<16}: {val:.4f}  {bar}{tag}")

# ベイズ系の最良
best_bayes = max(BAYES_MODELS.keys(),
                 key=lambda k: float(np.mean(cv_prec[k][ref_n])))
val_best_bayes = float(np.mean(cv_prec[best_bayes][ref_n]))
val_3stg       = float(np.mean(cv_prec["3Stg-25%"][ref_n]))
val_gb         = float(np.mean(cv_prec["GlobalBurau"][ref_n]))

print(f"\n  [ベイズ系の最良: {best_bayes}  Precision@{ref_n}={val_best_bayes:.4f}]")
if val_best_bayes > val_3stg:
    print(f"  → ベイズ系が 3-Stage 解析を上回った！")
elif val_best_bayes > val_gb:
    print(f"  → ベイズ系は GlobalBurau を上回るが 3-Stage には届かず")
else:
    print(f"  → ベイズ系も GlobalBurau に届かず。解析的アプローチが優位")

print(f"\n  [特徴量の重みについて]")
br = copy.deepcopy(ALL_MODELS["BayesianRidge"][_sage_const_1 ]); br.fit(X, y_reg)
ard = copy.deepcopy(ALL_MODELS["ARD"][_sage_const_1 ]); ard.fit(X, y_reg)
ct_feats = ["max_cycle_len","n_cycles","n_fixed"]
for name, m in [("BayesianRidge", br), ("ARD", ard)]:
    ct_w  = sum(abs(m.coef_[FEATURE_NAMES.index(f)]) for f in ct_feats)
    bur_w = abs(m.coef_[FEATURE_NAMES.index("burau")])
    print(f"  {name}: cycle_type系={ct_w:.4f}  Burau={bur_w:.4f}  "
          + ("→ Burau支配" if bur_w > ct_w else "→ cycle_type支配"))

print("\n" + "=" * _sage_const_65 )
print(f"  W-7k 実験完了  出力先: {OUT}")
print("=" * _sage_const_65 )

