

# This file was *autogenerated* from the file exp_W7e.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65 = Integer(65); _sage_const_55 = Integer(55); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_100 = Integer(100); _sage_const_0 = Integer(0); _sage_const_42 = Integer(42); _sage_const_24 = Integer(24); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_0p85 = RealNumber('0.85'); _sage_const_25 = Integer(25); _sage_const_3p0 = RealNumber('3.0'); _sage_const_720 = Integer(720); _sage_const_0p0 = RealNumber('0.0'); _sage_const_18 = Integer(18); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_0p046 = RealNumber('0.046'); _sage_const_120 = Integer(120); _sage_const_15 = Integer(15); _sage_const_10 = Integer(10); _sage_const_75 = Integer(75); _sage_const_30 = Integer(30); _sage_const_150 = Integer(150); _sage_const_0p8287 = RealNumber('0.8287'); _sage_const_0p7226 = RealNumber('0.7226'); _sage_const_0p5651 = RealNumber('0.5651'); _sage_const_14 = Integer(14); _sage_const_11 = Integer(11); _sage_const_50 = Integer(50)#!/usr/bin/env sage
# exp_W7e.sage — W-7e: B₆ (6 strands, 720 permutations) × Intervention Landscape
# スケーリング則: B₃(n=6,r=-0.83)→B₄(n=24,r=-0.72)→B₅(n=120,r=-0.57)→B₆(n=720,r=?)

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from pathlib import Path
from sage.combinat.permutation import Permutation as SagePerm
from itertools import permutations as iter_perms

print("=" * _sage_const_65 )
print("  W-7e: B₆ × Intervention Landscape (720 permutations)")
print("  スケーリング則の延長: r はさらに低下するか？")
print("=" * _sage_const_65 )

OUT = Path("/mnt/c/Users/yoshi/don_theory/lab/wild/results/W7e")
OUT.mkdir(parents=True, exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# Part 1: B₆ の全 720 置換ブレイドと Burau trace
# ══════════════════════════════════════════════════════════════════
print("\n[Part 1] B₆ の全 720 置換ブレイドと Burau trace")
print("-" * _sage_const_55 )

B6   = BraidGroup(_sage_const_6 )
gens = list(B6.generators())   # σ₁, σ₂, σ₃, σ₄, σ₅
t    = var('t')

all_perms = list(iter_perms([_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_6 ]))   # 720 通り

print("  Burau trace を計算中 (720 件)...")
perm_info = []
for k, perm in enumerate(all_perms):
    sp    = SagePerm(list(perm))
    word  = sp.reduced_word()
    b     = B6.one()
    for i in word:
        b = b * gens[i - _sage_const_1 ]
    bmat   = b.burau_matrix()(t=QQ(_sage_const_1 )/QQ(_sage_const_2 ))
    btr    = float(bmat.trace())
    writhe = len(word)
    perm_info.append({
        "perm":   list(perm),
        "label":  "".join(str(x) for x in perm),
        "word":   word,
        "burau":  btr,
        "writhe": writhe,
        "order":  [x - _sage_const_1  for x in perm],
    })
    if (k + _sage_const_1 ) % _sage_const_100  == _sage_const_0 :
        print(f"  ... {k+_sage_const_1 }/720 完了")

burau_all  = np.array([p["burau"]  for p in perm_info])
writhe_all = np.array([p["writhe"] for p in perm_info])
print(f"  完了。Burau trace: [{burau_all.min():.4f}, {burau_all.max():.4f}]")
print(f"  Writhe:           [{int(writhe_all.min())}, {int(writhe_all.max())}]")

# ══════════════════════════════════════════════════════════════════
# Part 2: 損失景観 J(θ) の計算（全 720 順序）
# ══════════════════════════════════════════════════════════════════
print("\n[Part 2] 損失景観 J(θ) の計算")
print("-" * _sage_const_55 )

rng = np.random.default_rng(int(_sage_const_42 ))
d   = _sage_const_24 

A_dyn  = rng.standard_normal((d, d)) * _sage_const_0p25 
A_dyn  = A_dyn - A_dyn.T
b_bias = rng.standard_normal(d) * _sage_const_0p1 

def time_evolution(p):
    return np.tanh(A_dyn @ p + b_bias) * _sage_const_0p5  + p * _sage_const_0p4 

a_vec  = np.zeros(d);  a_vec[:d//_sage_const_4 ] = _sage_const_1p0 
M_mat  = rng.standard_normal((d, d)) * _sage_const_0p3 
M_mat  = M_mat / (np.linalg.norm(M_mat, _sage_const_2 ) + _sage_const_1en8 )
bias4  = rng.standard_normal(d) * _sage_const_0p3 
bias5  = rng.standard_normal(d) * _sage_const_0p2 
bias6  = rng.standard_normal(d) * _sage_const_0p25    # E6 専用

def E1(p, th): return p + th * a_vec
def E2(p, th): return (np.eye(d) + th * M_mat) @ p
def E3(p):     return np.tanh(p * _sage_const_1p2 ) * _sage_const_0p9 
def E4(p):     return np.tanh(p * _sage_const_0p8  + bias4) * _sage_const_0p7 
def E5(p):     return p * _sage_const_0p6  + np.tanh(bias5) * _sage_const_0p4 
def E6(p):     return np.tanh(p + bias6) * _sage_const_0p85   # 新規

N_ROUNDS = _sage_const_2           # 各ラウンド = 6 介入
T_total  = N_ROUNDS * _sage_const_6    # 12 ステップ

def apply_order(order, theta, p0):
    p    = p0.copy()
    traj = [p.copy()]
    for _ in range(N_ROUNDS):
        for idx in order:
            p = time_evolution(p)
            if   idx == _sage_const_0 : p = E1(p, theta[_sage_const_0 ])
            elif idx == _sage_const_1 : p = E2(p, theta[_sage_const_1 ])
            elif idx == _sage_const_2 : p = E3(p)
            elif idx == _sage_const_3 : p = E4(p)
            elif idx == _sage_const_4 : p = E5(p)
            else:          p = E6(p)
            traj.append(p.copy())
    return np.array(traj)

def compute_J(order, theta, p0, z_target):
    traj = apply_order(order, theta, p0)
    return float(np.mean(np.sum((traj - z_target)**_sage_const_2 , axis=_sage_const_1 )))

theta_star = np.array([_sage_const_1p0 , _sage_const_1p0 ])
p0         = rng.standard_normal(d) * _sage_const_0p5 
ref_order  = [_sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ]
z_target   = apply_order(ref_order, theta_star, p0)

N_GRID  = _sage_const_25 
th1_arr = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)
th2_arr = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)
TH1, TH2 = np.meshgrid(th1_arr, th2_arr)

# J をフラット配列で持つ（メモリ節約）
all_J_flat = np.zeros((_sage_const_720 , N_GRID * N_GRID))
ref_land   = None

print(f"  グリッド: {N_GRID}×{N_GRID},  d={d},  T={T_total},  n_perms=720")
print(f"  計算中 (720 × {N_GRID}×{N_GRID} = {_sage_const_720 *N_GRID*N_GRID} 点)...")

for k, info in enumerate(perm_info):
    order  = info["order"]
    J_grid = np.array([
        [compute_J(order, [th1_arr[j], th2_arr[i]], p0, z_target)
         for j in range(N_GRID)]
        for i in range(N_GRID)
    ])
    all_J_flat[k] = J_grid.ravel()
    j_min  = float(J_grid.min())
    j_star = compute_J(order, theta_star, p0, z_target)
    if ref_land is None:
        ref_land = J_grid.ravel();  dist = _sage_const_0p0 
    else:
        dist = float(np.sqrt(np.mean((J_grid.ravel() - ref_land)**_sage_const_2 )))
    info["j_min"]  = j_min
    info["j_star"] = j_star
    info["dist"]   = dist
    if (k + _sage_const_1 ) % _sage_const_100  == _sage_const_0 :
        print(f"  ... {k+_sage_const_1 }/720 完了")

dist_all  = np.array([info["dist"]  for info in perm_info])
print(f"  完了。景観距離: [{dist_all.min():.4f}, {dist_all.max():.4f}]")

# ══════════════════════════════════════════════════════════════════
# Part 3: 可視化
# ══════════════════════════════════════════════════════════════════
print("\n[Part 3] 可視化")
print("-" * _sage_const_55 )

labels      = [info["label"]  for info in perm_info]
burau_vals  = np.array([info["burau"]  for info in perm_info])
dist_vals   = np.array([info["dist"]   for info in perm_info])
writhe_vals = np.array([info["writhe"] for info in perm_info])

r_b, p_b    = stats.pearsonr(burau_vals, dist_vals)
r_w, p_w    = stats.pearsonr(writhe_vals, dist_vals)
slope_b, intercept_b, *_ = stats.linregress(burau_vals, dist_vals)

# 図1: 代表景観 — Burau 上位 6 + 下位 6
sorted_asc = sorted(perm_info, key=lambda x: x["burau"])
rep12      = sorted_asc[-_sage_const_6 :] + sorted_asc[:_sage_const_6 ]

fig, axes = plt.subplots(_sage_const_3 , _sage_const_4 , figsize=(_sage_const_18 , _sage_const_13 ))
fig.suptitle("W-7e: B6 Loss Landscapes\n"
             "Top 6 Burau (simple) + Bottom 6 Burau (complex)", fontsize=_sage_const_12 )
for ax, info in zip(axes.flat, rep12):
    idx = labels.index(info["label"])
    J   = all_J_flat[idx].reshape(N_GRID, N_GRID)
    im  = ax.contourf(TH1, TH2, J, levels=_sage_const_18 , cmap="viridis")
    ax.contour(TH1, TH2, J, levels=_sage_const_6 , colors="white", alpha=_sage_const_0p3 , linewidths=_sage_const_0p5 )
    ax.plot(*theta_star, "r*", ms=_sage_const_9 )
    ax.set_title(f"{info['label']}  Burau={info['burau']:.3f}\n"
                 f"dist={info['dist']:.3f}", fontsize=_sage_const_8 )
    ax.set_xlabel("theta1", fontsize=_sage_const_7 );  ax.set_ylabel("theta2", fontsize=_sage_const_7 )
    plt.colorbar(im, ax=ax, fraction=_sage_const_0p046 )
plt.tight_layout()
p = OUT / "W7e_fig1_landscapes.png"
fig.savefig(str(p), dpi=_sage_const_120 , bbox_inches="tight");  plt.close()
print(f"  fig1 saved: {p}")

# 図2: メイン相関図（n=720）
fig, axes = plt.subplots(_sage_const_1 , _sage_const_2 , figsize=(_sage_const_15 , _sage_const_6 ))
fig.suptitle(f"W-7e: B6 Braid Invariant vs Loss Landscape  (n=720)", fontsize=_sage_const_12 )

ax = axes[_sage_const_0 ]
ax.scatter(burau_vals, dist_vals, c=writhe_vals, cmap="plasma",
           s=_sage_const_8 , alpha=_sage_const_0p5 , zorder=_sage_const_5 )
x_line = np.linspace(burau_vals.min(), burau_vals.max(), _sage_const_100 )
ax.plot(x_line, slope_b * x_line + intercept_b, "r-", alpha=_sage_const_0p9 , lw=_sage_const_2 ,
        label=f"r={r_b:.4f}")
plt.colorbar(
    plt.cm.ScalarMappable(cmap="plasma",
        norm=plt.Normalize(writhe_vals.min(), writhe_vals.max())),
    ax=ax, label="Writhe")
ax.set_xlabel("Burau trace (t=1/2)")
ax.set_ylabel("Landscape distance from identity (RMSE)")
ax.set_title(f"Burau trace:  r = {r_b:.4f},  p = {p_b:.2e}\n"
             f"B3:-0.83  B4:-0.72  B5:-0.57  B6:{r_b:.4f}", fontsize=_sage_const_10 )
ax.legend(fontsize=_sage_const_9 );  ax.grid(True, alpha=_sage_const_0p3 )

# 距離分布を Burau trace 四分位で色分けヒストグラム
ax2 = axes[_sage_const_1 ]
q25, q75 = np.percentile(burau_vals, [_sage_const_25 , _sage_const_75 ])
mask_hi = burau_vals >= q75      # 上位 25%（単純な braid）
mask_lo = burau_vals <= q25      # 下位 25%（複雑な braid）
mask_mid = ~mask_hi & ~mask_lo

bins = np.linspace(dist_vals.min(), dist_vals.max(), _sage_const_30 )
ax2.hist(dist_vals[mask_hi],  bins=bins, alpha=_sage_const_0p6 , color="steelblue",
         label=f"Burau top 25% (simple, n={mask_hi.sum()})")
ax2.hist(dist_vals[mask_mid], bins=bins, alpha=_sage_const_0p4 , color="gray",
         label=f"Burau mid 50% (n={mask_mid.sum()})")
ax2.hist(dist_vals[mask_lo],  bins=bins, alpha=_sage_const_0p6 , color="tomato",
         label=f"Burau bot 25% (complex, n={mask_lo.sum()})")
ax2.set_xlabel("Landscape distance from identity")
ax2.set_ylabel("Count")
ax2.set_title("Distance distribution by Burau quartile", fontsize=_sage_const_10 )
ax2.legend(fontsize=_sage_const_8 );  ax2.grid(True, alpha=_sage_const_0p3 )

plt.tight_layout()
p = OUT / "W7e_fig2_correlation.png"
fig.savefig(str(p), dpi=_sage_const_150 , bbox_inches="tight");  plt.close()
print(f"  fig2 saved: {p}")

# 図3: スケーリング則（B₃→B₄→B₅→B₆）
SCALING = [
    ("B3", _sage_const_3 ,   _sage_const_6 , -_sage_const_0p8287 , -_sage_const_0p8287 ),
    ("B4", _sage_const_4 ,  _sage_const_24 , -_sage_const_0p7226 , -_sage_const_0p7226 ),
    ("B5", _sage_const_5 , _sage_const_120 , -_sage_const_0p5651 , -_sage_const_0p5651 ),
    ("B6", _sage_const_6 , _sage_const_720 ,  r_b,     r_b),
]
ns  = [s[_sage_const_2 ] for s in SCALING]
rs  = [s[_sage_const_3 ] for s in SCALING]
Ks  = [s[_sage_const_1 ] for s in SCALING]

fig, axes = plt.subplots(_sage_const_1 , _sage_const_2 , figsize=(_sage_const_14 , _sage_const_5 ))
fig.suptitle("W-7: Scaling Law  B3 → B4 → B5 → B6", fontsize=_sage_const_12 )

ax = axes[_sage_const_0 ]
ax.plot(ns, [abs(r) for r in rs], "o-", ms=_sage_const_10 , lw=_sage_const_2 , color="steelblue")
for n_val, r_val, (name, K, *_) in zip(ns, rs, SCALING):
    ax.annotate(f"{name}\nr={r_val:.4f}",
                (n_val, abs(r_val)), textcoords="offset points",
                xytext=(_sage_const_8 , -_sage_const_15 ), fontsize=_sage_const_9 )
ax.set_xscale("log")
ax.set_xlabel("n (permutations = K!)", fontsize=_sage_const_11 )
ax.set_ylabel("|Pearson r|", fontsize=_sage_const_11 )
ax.set_title("Correlation magnitude vs n\n(log scale)", fontsize=_sage_const_10 )
ax.grid(True, alpha=_sage_const_0p3 );  ax.set_ylim(_sage_const_0 , _sage_const_1 )

ax2 = axes[_sage_const_1 ]
ax2.plot(Ks, [abs(r) for r in rs], "s-", ms=_sage_const_10 , lw=_sage_const_2 , color="tomato")
for K_val, r_val, (name, *_) in zip(Ks, rs, SCALING):
    ax2.annotate(f"{name}\nr={r_val:.4f}",
                 (K_val, abs(r_val)), textcoords="offset points",
                 xytext=(_sage_const_5 , _sage_const_5 ), fontsize=_sage_const_9 )
ax2.set_xlabel("K (number of interventions = strands)", fontsize=_sage_const_11 )
ax2.set_ylabel("|Pearson r|", fontsize=_sage_const_11 )
ax2.set_title("|r| vs K (number of strands)", fontsize=_sage_const_10 )
ax2.grid(True, alpha=_sage_const_0p3 );  ax2.set_ylim(_sage_const_0 , _sage_const_1 )

plt.tight_layout()
p = OUT / "W7e_fig3_scaling.png"
fig.savefig(str(p), dpi=_sage_const_150 , bbox_inches="tight");  plt.close()
print(f"  fig3 saved: {p}")

# 図4: 先頭介入ごとの距離分布（E1 が先頭か？）
fig, ax = plt.subplots(figsize=(_sage_const_10 , _sage_const_5 ))
first_elem = [info["order"][_sage_const_0 ] for info in perm_info]  # 0-indexed
colors6 = plt.cm.tab10(np.linspace(_sage_const_0 , _sage_const_0p6 , _sage_const_6 ))
for e in range(_sage_const_6 ):
    mask  = np.array(first_elem) == e
    dvals = dist_vals[mask]
    ax.scatter(np.full(mask.sum(), e), dvals, alpha=_sage_const_0p3 , s=_sage_const_15 ,
               color=colors6[e], zorder=_sage_const_3 )
    ax.plot([e - _sage_const_0p3 , e + _sage_const_0p3 ], [dvals.mean(), dvals.mean()],
            lw=_sage_const_3 , color=colors6[e], zorder=_sage_const_5 ,
            label=f"E{e+_sage_const_1 } first: mean={dvals.mean():.2f}")

ax.set_xticks(range(_sage_const_6 ))
ax.set_xticklabels([f"E{i+_sage_const_1 } first" for i in range(_sage_const_6 )])
ax.set_ylabel("Landscape distance from identity")
ax.set_title("B6: Distance distribution by first intervention\n"
             "(horizontal lines = means)")
ax.legend(fontsize=_sage_const_8 , loc="upper right");  ax.grid(True, alpha=_sage_const_0p3 )
plt.tight_layout()
p = OUT / "W7e_fig4_first_elem.png"
fig.savefig(str(p), dpi=_sage_const_150 , bbox_inches="tight");  plt.close()
print(f"  fig4 saved: {p}")

# ══════════════════════════════════════════════════════════════════
# Part 4: 統計サマリー
# ══════════════════════════════════════════════════════════════════
print("\n[Part 4] 統計サマリー")
print("-" * _sage_const_65 )

max_dist = dist_all.max()
max_idx  = int(dist_all.argmax())
nearest  = sorted(perm_info[_sage_const_1 :], key=lambda x: x["dist"])[_sage_const_0 ]

# 先頭介入ごとの平均距離
first_means = []
for e in range(_sage_const_6 ):
    mask = np.array([info["order"][_sage_const_0 ] for info in perm_info]) == e
    first_means.append((e + _sage_const_1 , dist_vals[mask].mean(), mask.sum()))

print(f"""
  ━━ Burau trace vs 景観距離 (n=720) ━━
  Pearson r  = {r_b:.4f}
  p-value    = {p_b:.2e}

  ━━ Writhe vs 景観距離 ━━
  Pearson r  = {r_w:.4f}
  p-value    = {p_w:.2e}

  ━━ スケーリング則まとめ ━━
  B₃ (K=_sage_const_3 , n=  _sage_const_6 ):  r = -_sage_const_0p8287 
  B₄ (K=_sage_const_4 , n= _sage_const_24 ):  r = -_sage_const_0p7226 
  B₅ (K=_sage_const_5 , n=_sage_const_120 ):  r = -_sage_const_0p5651 
  B₆ (K=_sage_const_6 , n=_sage_const_720 ):  r = {r_b:.4f}

  ━━ 景観統計 ━━
  距離の平均: {dist_all.mean():.4f}
  距離の最大: {max_dist:.4f}  ({labels[max_idx]})
  identity に最近傍: {nearest['label']}  (dist={nearest['dist']:.4f})

  ━━ 先頭介入ごとの平均景観距離 ━━""")

for e, mean_d, cnt in sorted(first_means, key=lambda x: x[_sage_const_1 ]):
    bar = "█" * int(mean_d * _sage_const_3 )
    print(f"  E{e} first: {mean_d:.4f}  {bar}")

print(f"""
  ━━ Burau 四分位ごとの距離統計 ━━
  上位 25% (simple):  mean={dist_vals[mask_hi].mean():.4f}  std={dist_vals[mask_hi].std():.4f}
  中位 _sage_const_50 %:           mean={dist_vals[mask_mid].mean():.4f}  std={dist_vals[mask_mid].std():.4f}
  下位 _sage_const_25 % (complex): mean={dist_vals[mask_lo].mean():.4f}  std={dist_vals[mask_lo].std():.4f}
""")

print("=" * _sage_const_65 )
print(f"  W-7e 実験完了  出力先: {OUT}")
print("=" * _sage_const_65 )

