

# This file was *autogenerated* from the file exp_W7j.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65 = Integer(65); _sage_const_42 = Integer(42); _sage_const_24 = Integer(24); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_4 = Integer(4); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_2 = Integer(2); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_25 = Integer(25); _sage_const_3p0 = RealNumber('3.0'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_0p85 = RealNumber('0.85'); _sage_const_6 = Integer(6); _sage_const_55 = Integer(55); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_0p0 = RealNumber('0.0'); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_150 = Integer(150); _sage_const_7 = Integer(7); _sage_const_13 = Integer(13); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_40 = Integer(40); _sage_const_12 = Integer(12); _sage_const_9 = Integer(9); _sage_const_120 = Integer(120); _sage_const_2p0 = RealNumber('2.0'); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p12 = RealNumber('0.12'); _sage_const_1p05 = RealNumber('1.05'); _sage_const_0p92 = RealNumber('0.92'); _sage_const_30 = Integer(30)#!/usr/bin/env sage
# exp_W7j.sage — ML vs 解析的スクリーニング（SVM / RF / XGBoost）
# 問いA: MLは3-Stageより良い選択ができるか？
# 問いB: MLは cycle type 構造を自動的に発見できるか？（特徴量重要度）
# 設計: K=6 (720件), 5-fold CV, デフォルトパラメータ固定, チューニングなし

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from collections import defaultdict
from pathlib import Path
from sage.combinat.permutation import Permutation as SagePerm
from itertools import permutations as iter_perms

from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, cross_val_score
from sklearn.inspection import permutation_importance
import xgboost as xgb

print("=" * _sage_const_65 )
print("  W-7j: ML vs 解析的スクリーニング")
print("  SVM / RandomForest / XGBoost (デフォルトパラメータ)")
print("  5-fold CV  ·  特徴量重要度  ·  Precision@N 比較")
print("=" * _sage_const_65 )

OUT = Path("/mnt/c/Users/yoshi/don_theory/lab/wild/results/W7j")
OUT.mkdir(parents=True, exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# 数値セットアップ（同一 seed）
# ══════════════════════════════════════════════════════════════════
rng = np.random.default_rng(int(_sage_const_42 ))
d   = _sage_const_24 
A_dyn  = rng.standard_normal((d,d))*_sage_const_0p25 ;  A_dyn = A_dyn - A_dyn.T
b_bias = rng.standard_normal(d)*_sage_const_0p1 
a_vec  = np.zeros(d);  a_vec[:d//_sage_const_4 ] = _sage_const_1p0 
M_mat  = rng.standard_normal((d,d))*_sage_const_0p3 
M_mat  = M_mat / (np.linalg.norm(M_mat,_sage_const_2 )+_sage_const_1en8 )
bias_list = [rng.standard_normal(d)*(_sage_const_0p2 +_sage_const_0p05 *i) for i in range(_sage_const_4 )]
theta_star = np.array([_sage_const_1p0 , _sage_const_1p0 ])
p0_master  = rng.standard_normal(d)*_sage_const_0p5 
N_ROUNDS = _sage_const_2 ;  N_GRID = _sage_const_25 
th1 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)
th2 = np.linspace(-_sage_const_1p0 , _sage_const_3p0 , N_GRID)

def time_ev(p): return np.tanh(A_dyn@p+b_bias)*_sage_const_0p5 +p*_sage_const_0p4 
def make_ops(K):
    return [
        lambda p,th,_=None: p+th[_sage_const_0 ]*a_vec,
        lambda p,th,_=None: (np.eye(d)+th[_sage_const_1 ]*M_mat)@p,
        lambda p,th,_=None: np.tanh(p*_sage_const_1p2 )*_sage_const_0p9 ,
        lambda p,th,_=None: np.tanh(p*_sage_const_0p8 +bias_list[_sage_const_0 ])*_sage_const_0p7 ,
        lambda p,th,_=None: p*_sage_const_0p6 +np.tanh(bias_list[_sage_const_1 ])*_sage_const_0p4 ,
        lambda p,th,_=None: np.tanh(p+bias_list[_sage_const_2 ])*_sage_const_0p85 ,
    ][:K]

def compute_dist(order, K):
    ops = make_ops(K);  p0 = p0_master.copy()
    ref = list(range(K))
    def traj(ord_, th):
        p = p0.copy();  t = [p.copy()]
        for _ in range(N_ROUNDS):
            for idx in ord_:
                p = time_ev(p);  p = ops[idx](p,th);  t.append(p.copy())
        return np.array(t)
    zt = traj(ref, theta_star)
    def J(ord_, th): return float(np.mean(np.sum((traj(ord_,th)-zt)**_sage_const_2 ,axis=_sage_const_1 )))
    grid = np.array([[J(order,[th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    ref_g= np.array([[J(ref,  [th1[j],th2[i]]) for j in range(N_GRID)]
                     for i in range(N_GRID)])
    return float(np.sqrt(np.mean((grid.ravel()-ref_g.ravel())**_sage_const_2 )))

# ══════════════════════════════════════════════════════════════════
# データ構築: K=6 のみ
# ══════════════════════════════════════════════════════════════════
K = _sage_const_6 
print(f"\n[K={K}] 全 {factorial(K)} 件のデータ構築中...")
BK = BraidGroup(K);  gK = list(BK.generators())
rows = []
for perm in iter_perms(range(_sage_const_1 , K+_sage_const_1 )):
    sp   = SagePerm(list(perm))
    b    = BK.one()
    for i in sp.reduced_word(): b = b * gK[i-_sage_const_1 ]
    btr  = float(b.burau_matrix()(t=QQ(_sage_const_1 )/QQ(_sage_const_2 )).trace())
    ct   = list(sp.cycle_type())          # e.g. [3,2,1]
    dist = compute_dist([x-_sage_const_1  for x in perm], K)
    rows.append({
        "perm"          : list(perm),
        "label"         : "".join(str(x) for x in perm),
        "burau"         : btr,
        "writhe"        : len(sp.reduced_word()),
        "max_cycle_len" : int(max(ct)),
        "n_cycles"      : len(ct),
        "n_fixed"       : int(ct.count(_sage_const_1 )),
        "ct_str"        : str(ct),
        "dist"          : dist,
    })
dists = [r["dist"] for r in rows]
print(f"  完了。dist: [{min(dists):.3f}, {max(dists):.3f}]  mean={np.mean(dists):.3f}")

# ══════════════════════════════════════════════════════════════════
# 特徴量行列と正解ラベルの準備
# ══════════════════════════════════════════════════════════════════
FEATURE_NAMES = ["burau", "writhe", "max_cycle_len", "n_cycles", "n_fixed"]
X_raw = np.array([[r[f] for f in FEATURE_NAMES] for r in rows])
y     = np.array([r["dist"] for r in rows])

scaler = StandardScaler()
X      = scaler.fit_transform(X_raw)

print(f"\n  特徴量: {FEATURE_NAMES}")
print(f"  X.shape={X.shape}  y.shape={y.shape}")
print(f"  Pearson r (burau vs dist): "
      f"{stats.pearsonr(X_raw[:,_sage_const_0 ], y)[_sage_const_0 ]:.4f}")

# ══════════════════════════════════════════════════════════════════
# モデル定義（デフォルトパラメータ固定）
# ══════════════════════════════════════════════════════════════════
MODELS = {
    "SVR-RBF"  : SVR(),                          # C=1.0, gamma='scale'
    "RF"       : RandomForestRegressor(random_state=_sage_const_0 ),  # n_est=100
    "GBM"      : GradientBoostingRegressor(random_state=_sage_const_0 ),
    "XGBoost"  : xgb.XGBRegressor(random_state=int(_sage_const_0 ), verbosity=int(_sage_const_0 )),
}

# ══════════════════════════════════════════════════════════════════
# 5-fold CV: dist 予測精度
# ══════════════════════════════════════════════════════════════════
print("\n[5-fold CV: 回帰精度 (dist 予測)]")
print(f"  {'モデル':<12} | {'MAE mean':<12} | {'R² mean':<12} | R² std")
print("  " + "-"*_sage_const_55 )

cv_results = {}
kf = KFold(n_splits=_sage_const_5 , shuffle=True, random_state=_sage_const_42 )

for name, model in MODELS.items():
    r2_scores  = cross_val_score(model, X, y, cv=kf, scoring="r2")
    mae_scores = -cross_val_score(model, X, y, cv=kf, scoring="neg_mean_absolute_error")
    cv_results[name] = {"r2_mean": float(r2_scores.mean()),
                        "r2_std" : float(r2_scores.std()),
                        "mae_mean": float(mae_scores.mean())}
    print(f"  {name:<12} | {mae_scores.mean():.4f}±{mae_scores.std():.4f}   "
          f"| {r2_scores.mean():.4f}±{r2_scores.std():.4f}")

# 参考: burau 単一の線形回帰
from sklearn.linear_model import LinearRegression
lr_r2 = cross_val_score(LinearRegression(), X[:,[_sage_const_0 ]], y, cv=kf, scoring="r2")
print(f"  {'Linear(burau)':<12} | {'—':<12} | {lr_r2.mean():.4f}±{lr_r2.std():.4f}"
      f"  ← Burau単体ベースライン")

# ══════════════════════════════════════════════════════════════════
# 全データ学習 → 上位 N 件選択での Precision@N
# （CV 推定ではなく "全件知っている場合" の理論上限も確認）
# ══════════════════════════════════════════════════════════════════
print("\n[Precision@N: 全データ学習後の選択精度]")
print("  ※ 全720件を学習して同720件をランキング — 過学習込みの上限値")

def oracle_top(rows, N):
    return {r["label"] for r in sorted(rows, key=lambda r: r["dist"])[:N]}

def burau_3stage_top(rows, N):
    """W-7i の 3-Stage-25% を再現"""
    all_dists = np.array([r["dist"] for r in rows])
    dist_thr  = float(np.percentile(all_dists, _sage_const_25 ))
    # cycle type の mean_dist を計算
    ct_mean = defaultdict(list)
    for r in rows: ct_mean[r["ct_str"]].append(r["dist"])
    kept_cts = {ct for ct, dv in ct_mean.items()
                if float(np.mean(dv)) <= dist_thr}
    kept = [r for r in rows if r["ct_str"] in kept_cts]
    # within-type Burau 降順
    ct_grp = defaultdict(list)
    for r in kept: ct_grp[r["ct_str"]].append(r)
    selected = []
    for ct, grp in ct_grp.items():
        bv = np.array([r["burau"] for r in grp])
        dv = np.array([r["dist"]  for r in grp])
        rr = stats.pearsonr(bv, dv)[_sage_const_0 ] if len(grp) >= _sage_const_3  else _sage_const_0p0 
        direction = -_sage_const_1  if rr > _sage_const_0  else +_sage_const_1 
        n_sel = int(max(_sage_const_1 , round(N * len(grp) / len(kept))))
        ranked = sorted(grp, key=lambda r: direction * r["burau"], reverse=True)
        selected.extend(ranked[:n_sel])
    if len(selected) > N:
        selected = sorted(selected, key=lambda r: r["dist"])[:N]
    elif len(selected) < N:
        sel_lbl = {r["label"] for r in selected}
        rem = sorted([r for r in rows if r["label"] not in sel_lbl],
                     key=lambda r: r["dist"])
        selected.extend(rem[:N - len(selected)])
    return {r["label"] for r in selected[:N]}

def global_burau_top(rows, N):
    bv = np.array([r["burau"] for r in rows])
    dv = np.array([r["dist"]  for r in rows])
    direction = -_sage_const_1  if stats.pearsonr(bv, dv)[_sage_const_0 ] > _sage_const_0  else +_sage_const_1 
    sel = sorted(rows, key=lambda r: direction * r["burau"], reverse=True)[:N]
    return {r["label"] for r in sel}

N_vals = [_sage_const_10 , _sage_const_20 , _sage_const_50 , _sage_const_100 , _sage_const_150 ]
labels_all = [r["label"] for r in rows]

# ML モデルを全データで学習してランキング
fitted = {}
for name, model in MODELS.items():
    model.fit(X, y)
    fitted[name] = model

print(f"\n  {'N_sel':<7}| {'GlobalBurau':<13}| {'3Stg-_sage_const_25 %':<13}| ", end="")
for name in MODELS: print(f"{name:<13}| ", end="")
print("Oracle")
print("  " + "-"*(_sage_const_7  + _sage_const_13 *(_sage_const_2 +len(MODELS)) + _sage_const_8 ))

prec_data = {k: [] for k in ["GlobalBurau","3Stg-25%","Oracle"] + list(MODELS.keys())}
for N in N_vals:
    true_top = oracle_top(rows, N)
    p_gb  = float(len(true_top & global_burau_top(rows, N))) / N
    p_3s  = float(len(true_top & burau_3stage_top(rows, N))) / N
    line  = f"  N={N:<5}| {p_gb:.3f}        | {p_3s:.3f}        | "
    prec_data["GlobalBurau"].append(p_gb)
    prec_data["3Stg-25%"].append(p_3s)
    for name, model in fitted.items():
        y_pred = model.predict(X)
        # 予測dist が小さい順に選ぶ
        top_idx = np.argsort(y_pred)[:N]
        ml_top  = {labels_all[i] for i in top_idx}
        p_ml    = float(len(true_top & ml_top)) / N
        prec_data[name].append(p_ml)
        line += f"{p_ml:.3f}        | "
    p_or = _sage_const_1p0 
    prec_data["Oracle"].append(p_or)
    line += f"{p_or:.3f}"
    print(line)

# ══════════════════════════════════════════════════════════════════
# 5-fold CV ベースの Precision@N（汎化性能）
# ══════════════════════════════════════════════════════════════════
print("\n[Precision@N: 5-fold CV ベース (汎化性能の推定)]")
print("  ※ test fold の予測値でランキング → train fold では見ていない件を選択")

cv_prec = {name: {N: [] for N in N_vals} for name in MODELS}
cv_prec["GlobalBurau"] = {N: [] for N in N_vals}
cv_prec["3Stg-25%"]    = {N: [] for N in N_vals}

for fold_idx, (train_idx, test_idx) in enumerate(kf.split(X)):
    X_tr, X_te = X[train_idx], X[test_idx]
    y_tr, y_te = y[train_idx], y[test_idx]
    rows_te = [rows[i] for i in test_idx]

    for N in N_vals:
        # Oracle for this fold
        true_top_fold = oracle_top(rows_te, min(N, len(rows_te)))

        # GlobalBurau & 3-Stage on test fold
        p_gb = float(len(true_top_fold & global_burau_top(rows_te, min(N, len(rows_te))))) / min(N, len(rows_te))
        p_3s = float(len(true_top_fold & burau_3stage_top(rows_te, min(N, len(rows_te))))) / min(N, len(rows_te))
        cv_prec["GlobalBurau"][N].append(p_gb)
        cv_prec["3Stg-25%"][N].append(p_3s)

        # ML モデルを train fold で学習 → test fold でランキング
        for name, base_model in MODELS.items():
            import copy
            m = copy.deepcopy(base_model)
            m.fit(X_tr, y_tr)
            y_pred_te = m.predict(X_te)
            n_sel = min(N, len(rows_te))
            top_idx = np.argsort(y_pred_te)[:n_sel]
            ml_top  = {rows_te[i]["label"] for i in top_idx}
            p_ml    = float(len(true_top_fold & ml_top)) / n_sel
            cv_prec[name][N].append(p_ml)

print(f"\n  {'N_sel':<7}| {'GlobalBurau':<16}| {'3Stg-_sage_const_25 %':<16}| ", end="")
for name in MODELS: print(f"{name:<16}| ", end="")
print()
print("  " + "-"*(_sage_const_7  + _sage_const_16 *(_sage_const_2 +len(MODELS))))
for N in N_vals:
    line = f"  N={N:<5}| "
    for key in ["GlobalBurau","3Stg-25%"] + list(MODELS.keys()):
        vals = cv_prec[key][N]
        line += f"{np.mean(vals):.3f}±{np.std(vals):.3f}     | "
    print(line)

# ══════════════════════════════════════════════════════════════════
# 特徴量重要度（問いB: どの特徴量が支配的か）
# ══════════════════════════════════════════════════════════════════
print("\n[特徴量重要度]")

# RF の組み込み重要度
rf_model = RandomForestRegressor(random_state=_sage_const_0 )
rf_model.fit(X, y)
rf_imp = rf_model.feature_importances_
print(f"\n  Random Forest (MDI impurity):")
for fn, imp in sorted(zip(FEATURE_NAMES, rf_imp), key=lambda x: -x[_sage_const_1 ]):
    bar = "█" * int(imp * _sage_const_40 )
    print(f"    {fn:<16}: {imp:.4f}  {bar}")

# XGBoost の組み込み重要度
xgb_model = xgb.XGBRegressor(random_state=int(_sage_const_0 ), verbosity=int(_sage_const_0 ))
xgb_model.fit(X, y)
xgb_imp = xgb_model.feature_importances_
print(f"\n  XGBoost (gain-based):")
for fn, imp in sorted(zip(FEATURE_NAMES, xgb_imp), key=lambda x: -x[_sage_const_1 ]):
    bar = "█" * int(imp * _sage_const_40 )
    print(f"    {fn:<16}: {imp:.4f}  {bar}")

# Permutation importance (SVR)
svr_model = SVR();  svr_model.fit(X, y)
pi = permutation_importance(svr_model, X, y, n_repeats=_sage_const_20 , random_state=_sage_const_0 )
print(f"\n  SVR-RBF (permutation importance):")
for fn, imp, std in sorted(
        zip(FEATURE_NAMES, pi.importances_mean, pi.importances_std),
        key=lambda x: -x[_sage_const_1 ]):
    bar = "█" * max(_sage_const_0 , int(imp * _sage_const_40 ))
    print(f"    {fn:<16}: {imp:.4f}±{std:.4f}  {bar}")

# ══════════════════════════════════════════════════════════════════
# 可視化
# ══════════════════════════════════════════════════════════════════
print("\n[可視化]")

# ── 図1: 特徴量重要度の比較 ─────────────────────────────────────
fig, axes = plt.subplots(_sage_const_1 , _sage_const_3 , figsize=(_sage_const_16 , _sage_const_5 ))
fig.suptitle("W-7j: Feature Importance — Which Feature Does ML Learn?", fontsize=_sage_const_12 )

importance_data = [
    ("RF (MDI)", rf_imp, None),
    ("XGBoost (gain)", xgb_imp, None),
    ("SVR (permutation)", pi.importances_mean, pi.importances_std),
]
for ax, (title, imp, err) in zip(axes, importance_data):
    order = np.argsort(imp)[::-_sage_const_1 ]
    colors = []
    for fn in [FEATURE_NAMES[i] for i in order]:
        if fn in ("max_cycle_len","n_cycles","n_fixed"):
            colors.append("#4CAF50")   # cycle type 系 → 緑
        elif fn == "burau":
            colors.append("#2196F3")   # Burau → 青
        else:
            colors.append("#FF9800")   # writhe → 橙
    if err is not None:
        ax.barh(range(len(FEATURE_NAMES)),
                [imp[i] for i in order],
                xerr=[err[i] for i in order],
                color=colors, alpha=_sage_const_0p8 )
    else:
        ax.barh(range(len(FEATURE_NAMES)),
                [imp[i] for i in order], color=colors, alpha=_sage_const_0p8 )
    ax.set_yticks(range(len(FEATURE_NAMES)))
    ax.set_yticklabels([FEATURE_NAMES[i] for i in order])
    ax.set_title(title)
    ax.set_xlabel("Importance")
    ax.axvline(_sage_const_0 , color='black', lw=_sage_const_0p5 )

# 凡例
from matplotlib.patches import Patch
legend_elems = [Patch(facecolor="#4CAF50", label="cycle type 系"),
                Patch(facecolor="#2196F3", label="Burau trace"),
                Patch(facecolor="#FF9800", label="Writhe")]
axes[_sage_const_2 ].legend(handles=legend_elems, loc="lower right", fontsize=_sage_const_9 )

plt.tight_layout()
fig.savefig(OUT / "W7j_fig1_feature_importance.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig1 saved: {OUT / 'W7j_fig1_feature_importance.png'}")

# ── 図2: Precision@N カーブ (CV ベース) ──────────────────────────
fig, ax = plt.subplots(figsize=(_sage_const_10 , _sage_const_6 ))
ax.set_title(f"W-7j: Precision@N — 5-fold CV  (K={K}, n=720)", fontsize=_sage_const_12 )

styles = {
    "GlobalBurau": ("blue",   "o", "--", _sage_const_2p0 ),
    "3Stg-25%":    ("green",  "s", "-",  _sage_const_2p0 ),
    "SVR-RBF":     ("purple", "^", "-",  _sage_const_1p5 ),
    "RF":          ("red",    "D", "-",  _sage_const_1p5 ),
    "GBM":         ("brown",  "v", "-",  _sage_const_1p5 ),
    "XGBoost":     ("orange", "P", "-",  _sage_const_1p5 ),
}
for key, (color, marker, ls, lw) in styles.items():
    means = [np.mean(cv_prec[key][N]) for N in N_vals]
    stds  = [np.std(cv_prec[key][N])  for N in N_vals]
    ax.plot(N_vals, means, marker=marker, ls=ls, color=color, lw=lw,
            label=key, alpha=_sage_const_0p85 )
    ax.fill_between(N_vals,
                    [m-s for m,s in zip(means,stds)],
                    [m+s for m,s in zip(means,stds)],
                    color=color, alpha=_sage_const_0p12 )

ax.set_xlabel("N (number selected out of 720)")
ax.set_ylabel("Precision@N (5-fold CV mean)")
ax.legend(fontsize=_sage_const_10 )
ax.grid(True, alpha=_sage_const_0p3 )
ax.set_ylim(_sage_const_0 , _sage_const_1p05 )

plt.tight_layout()
fig.savefig(OUT / "W7j_fig2_precision_cv.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig2 saved: {OUT / 'W7j_fig2_precision_cv.png'}")

# ── 図3: 全データ学習時の scatter (予測dist vs 真dist) ──────────
fig, axes = plt.subplots(_sage_const_2 , _sage_const_2 , figsize=(_sage_const_12 , _sage_const_10 ))
fig.suptitle("W-7j: Predicted vs True Distance (full-data fit)", fontsize=_sage_const_12 )

for ax, (name, model) in zip(axes.ravel(), fitted.items()):
    y_pred = model.predict(X)
    ax.scatter(y, y_pred, alpha=_sage_const_0p3 , s=_sage_const_10 , c=[r["max_cycle_len"] for r in rows],
               cmap="RdYlGn_r")
    rng_min = min(y.min(), y_pred.min())
    rng_max = max(y.max(), y_pred.max())
    ax.plot([rng_min, rng_max], [rng_min, rng_max], "k--", alpha=_sage_const_0p5 )
    r2 = cv_results[name]["r2_mean"]
    ax.set_title(f"{name}  (CV R²={r2:.3f})")
    ax.set_xlabel("True distance")
    ax.set_ylabel("Predicted distance")
    ax.text(_sage_const_0p05 , _sage_const_0p92 , f"color = max_cycle_len\n(green=small, red=large)",
            transform=ax.transAxes, fontsize=_sage_const_7 , alpha=_sage_const_0p7 )

plt.tight_layout()
fig.savefig(OUT / "W7j_fig3_scatter.png", dpi=_sage_const_120 , bbox_inches="tight")
plt.close(fig)
print(f"  fig3 saved: {OUT / 'W7j_fig3_scatter.png'}")

# ══════════════════════════════════════════════════════════════════
# 総合サマリー
# ══════════════════════════════════════════════════════════════════
print("\n" + "=" * _sage_const_65 )
print("  総合サマリー")
print("=" * _sage_const_65 )

print(f"\n  [CV R² — dist 予測精度]")
for name, res in cv_results.items():
    bar = "█" * int(max(_sage_const_0 , res['r2_mean']) * _sage_const_30 )
    print(f"    {name:<12}: R²={res['r2_mean']:.4f}  {bar}")
print(f"    {'Linear(Burau)':<12}: R²={lr_r2.mean():.4f}  (参考: Burau単体)")

print(f"\n  [CV Precision@N=50 比較]")
ranking = []
for key in ["GlobalBurau","3Stg-25%"] + list(MODELS.keys()):
    val = float(np.mean(cv_prec[key][_sage_const_50 ]))
    ranking.append((key, val))
for key, val in sorted(ranking, key=lambda x: -x[_sage_const_1 ]):
    bar = "█" * int(val * _sage_const_30 )
    print(f"    {key:<12}: {val:.4f}  {bar}")

print(f"\n  [問いB: cycle type 系 vs Burau の特徴量重要度]")
ct_features = ["max_cycle_len","n_cycles","n_fixed"]
ct_imp_rf  = sum(rf_imp[FEATURE_NAMES.index(f)] for f in ct_features)
bur_imp_rf = rf_imp[FEATURE_NAMES.index("burau")]
print(f"    RF:      cycle_type系合計={ct_imp_rf:.4f}  Burau={bur_imp_rf:.4f}")
ct_imp_xgb  = sum(xgb_imp[FEATURE_NAMES.index(f)] for f in ct_features)
bur_imp_xgb = xgb_imp[FEATURE_NAMES.index("burau")]
print(f"    XGBoost: cycle_type系合計={ct_imp_xgb:.4f}  Burau={bur_imp_xgb:.4f}")

if ct_imp_rf > bur_imp_rf:
    print(f"\n  ★ cycle type 系特徴量が Burau より支配的 → W-7i の解析と一致")
else:
    print(f"\n  ★ Burau が cycle type 系より支配的 → 解析的発見と異なる")

print(f"\n  [結論]")
best_ml     = max(((n, float(np.mean(cv_prec[n][_sage_const_50 ]))) for n in MODELS),
                  key=lambda x: x[_sage_const_1 ])
val_3stg    = float(np.mean(cv_prec["3Stg-25%"][_sage_const_50 ]))
val_gb      = float(np.mean(cv_prec["GlobalBurau"][_sage_const_50 ]))
val_best_ml = best_ml[_sage_const_1 ]
print(f"    GlobalBurau (解析)  : Precision@50 = {val_gb:.4f}")
print(f"    3-Stage-25% (解析)  : Precision@50 = {val_3stg:.4f}")
print(f"    {best_ml[_sage_const_0 ]:<12} (ML): Precision@50 = {val_best_ml:.4f}")
if val_best_ml > val_3stg:
    print(f"    → ML ({best_ml[_sage_const_0 ]}) が 3-Stage を上回る")
elif val_best_ml > val_gb:
    print(f"    → ML ({best_ml[_sage_const_0 ]}) が GlobalBurau を上回るが 3-Stage には届かず")
else:
    print(f"    → 解析的アプローチ (3-Stage) が ML を上回る")

print("\n" + "=" * _sage_const_65 )
print(f"  W-7j 実験完了  出力先: {OUT}")
print("=" * _sage_const_65 )

